Yaml

---
title: "Chapter 3: Tailoring Priors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chapter 2: Tailoring Priors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
  

## ----setup,echo = FALSE-------------------------------------------------------
library(glmbayes)
## Annette Dobson (1990) "An Introduction to Generalized Linear Models".
## Page 9: Plant Weight Data.
ctl    <- c(4.17, 5.58, 5.18, 6.11, 4.50, 4.61, 5.17, 4.53, 5.33, 5.14)
trt    <- c(4.81, 4.17, 4.41, 3.59, 5.87, 3.83, 6.03, 4.89, 4.32, 4.69)
group  <- gl(2, 10, 20, labels = c("Ctl", "Trt"))
weight <- c(ctl, trt)

dat <- data.frame(weight, group)
set.seed(333)

## ----Plant_Prior--------------------------------------------------------------
ps = Prior_Setup(
  weight ~ group, data = dat, family = gaussian(), pwt = 0.001,
  n_prior = NULL, sd = NULL,
  intercept_source = c("null_model", "full_model"),
  effects_source = c("null_effects", "full_model"),
  mu = NULL
)

#mu       = ps$mu
#V        = ps$Sigma
#disp_ML  = ps$dispersion

## ----Plant_w_intercept--------------------------------------------------------
lm.D9 <- lm(weight ~ group)
sumlm<-summary(lm.D9)
sumlm$coefficients

## ----Plant_lmb_call1----------------------------------------------------------
lmb.D9=lmb(weight ~ group,dNormal(mu=ps$mu,Sigma=ps$Sigma,dispersion=ps$dispersion),n=1000)
sumlmb<-summary(lmb.D9)
sumlmb$coefficients

## ----Plant_lmb_call2----------------------------------------------------------
lmb.D9=lmb(weight ~ group,dNormal(mu=ps$mu,Sigma=ps$Sigma,dispersion=ps$dispersion),n=100000)
sumlmb<-summary(lmb.D9)
sumlmb$coefficients

## ----MTCars Data--------------------------------------------------------------
data(mtcars)

# Create gallons per mile
mtcars$gpm <- 1 / mtcars$mpg

## ----MeanCenter---------------------------------------------------------------
# Mean-center predictors
#mtcars$c_hp <- scale(mtcars$hp, center = TRUE, scale = FALSE)
#mtcars$c_drat <- scale(mtcars$drat, center = TRUE, scale = FALSE)
#mtcars$c_qsec <- scale(mtcars$qsec, center = TRUE, scale = FALSE)

mtcars$c_wt  <- as.numeric(scale(mtcars$wt, center = TRUE, scale = FALSE))
mtcars$c_cyl <- as.numeric(scale(mtcars$cyl, center = TRUE, scale = FALSE))

## ----weight_v_gpm-------------------------------------------------------------

# Fit linear model
fit <- lm(gpm ~ c_wt, data = mtcars)

# Create scatter plot
plot(mtcars$c_wt, mtcars$gpm,
     pch = 19, col = "steelblue",
     xlab = "Mean-Centered Weight (c_wt)",
     ylab = "Gallons per Mile (gpm)",
     main = "Fuel Consumption vs. Mean-Centered Weight")

# Add regression line
abline(fit, col = "darkred", lwd = 2)

# Optional: Add confidence band manually
x_vals <- seq(min(mtcars$c_wt), max(mtcars$c_wt), length.out = 100)
pred <- predict(fit, newdata = data.frame(c_wt = x_vals), interval = "confidence")

lines(x_vals, pred[, "lwr"], col = "darkred", lty = 2)
lines(x_vals, pred[, "upr"], col = "darkred", lty = 2)


## ----cyl_v_gpm----------------------------------------------------------------
# Ensure gpm is defined
mtcars$gpm <- 1 / mtcars$mpg

# Create boxplot
boxplot(gpm ~ factor(cyl), data = mtcars,
        col = "lightblue", border = "darkblue",
        xlab = "Number of Cylinders",
        ylab = "Gallons per Mile (gpm)",
        main = "Fuel Consumption by Number of Cylinders")

# Add jittered points
set.seed(123)  # for reproducibility
points(jitter(as.numeric(factor(mtcars$cyl)), amount = 0.2), mtcars$gpm,
       pch = 19, col = rgb(70/255, 130/255, 180/255, alpha = 0.6))


## ----Mt_cars_Default_Prior----------------------------------------------------
# Use Prior_Setup to illustrate prior strength
pscars  <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data = mtcars,pwt=0.01) ## pwt=0.01-->n_prior= 32/99
pscars2 <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data = mtcars,pwt=0.5)  ## pwt=0.5-->n_prior= 32
pscars3 <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data = mtcars,pwt=0.55) ## pwt=0.55-->n_prior= 39.111

## ----print_priors-------------------------------------------------------------
pscars

## ----print_priors2------------------------------------------------------------
pscars2

## ----print_priors3------------------------------------------------------------
pscars3

## ----run_lmb------------------------------------------------------------------

set.seed(333)

lmb_cars<- lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars$mu,Sigma=pscars$Sigma, dispersion = pscars$dispersion),data =mtcars)
lmb_cars2<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars2$mu,Sigma=pscars2$Sigma, dispersion = pscars2$dispersion),data =mtcars)
lmb_cars3<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars3$mu,Sigma=pscars3$Sigma, dispersion = pscars3$dispersion),data =mtcars)


sum_lmbcars<-summary(lmb_cars)  
sum_lmbcars2<-summary(lmb_cars2)
sum_lmbcars3<-summary(lmb_cars3)


## ----sumlmb_out---------------------------------------------------------------
sum_lmbcars$coefficients

## ----sumlmb_out2--------------------------------------------------------------
sum_lmbcars2$coefficients

## ----sumlmb_out3--------------------------------------------------------------
sum_lmbcars3$coefficients

## ----Mt_cars_Default_Prior2---------------------------------------------------
# Use Prior_Setup to illustrate prior strength
pscars4 <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data = mtcars,n_prior=1)  ## n_prior=1--> pwt=0.0303
pscars5 <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data = mtcars,n_prior=10)  ## n_prior=10--> pwt=0.2381
pscars6 <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data = mtcars,n_prior=32)  ## n_prior=32--> pwt=0.5

set.seed(333)

lmb_cars4<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars4$mu,Sigma=pscars4$Sigma, dispersion = pscars4$dispersion),data =mtcars)
lmb_cars5<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars5$mu,Sigma=pscars5$Sigma, dispersion = pscars5$dispersion),data =mtcars)
lmb_cars6<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars6$mu,Sigma=pscars6$Sigma, dispersion = pscars6$dispersion),data =mtcars)

sum_lmbcars4<-summary(lmb_cars4)
sum_lmbcars5<-summary(lmb_cars5)
sum_lmbcars6<-summary(lmb_cars6)


## ----sumlmb_out4--------------------------------------------------------------
sum_lmbcars4$coefficients

## ----sumlmb_out5--------------------------------------------------------------
sum_lmbcars5$coefficients

## ----sumlmb_out6--------------------------------------------------------------
sum_lmbcars5$coefficients

## ----Mt_cars_sd_Prior1--------------------------------------------------------
pscars7 <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data =mtcars,sd=c(0.005,0.010,0.0015))  ## 
pscars7

## ----sumlmb_out7--------------------------------------------------------------

set.seed(333)
lmb_cars7<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars7$mu,Sigma=pscars7$Sigma, dispersion = pscars7$dispersion),data =mtcars)
sum_lmbcars7<-summary(lmb_cars7)
sum_lmbcars7

## ----Mt_cars_prior_full_model-------------------------------------------------
pscars8 <- Prior_Setup(formula = gpm ~  c_wt+c_cyl,family=gaussian(),data =mtcars,intercept_source = "full_model",effects_source = "full_model")  ## 
pscars8

## ----sumlmb_out8--------------------------------------------------------------

set.seed(333)
lmb_cars8<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars8$mu,Sigma=pscars8$Sigma, dispersion = pscars8$dispersion),data =mtcars)
sum_lmbcars8<-summary(lmb_cars8)
sum_lmbcars8

## ----Mt_cars_small------------------------------------------------------------
# Use Prior_Setup to illustrate prior strength
lmcars_small <- lm(formula = gpm ~  c_wt,  data = mtcars)
lmcars_small

## ----Mt_cars_Default_Prior5---------------------------------------------------
# Use Prior_Setup to illustrate prior strength
pscars9 <- Prior_Setup(  formula = gpm ~  c_wt+c_cyl,family=gaussian(),  data = mtcars,  pwt=0.01,mu=c(0.05423,0.01494,0))
pscars9

## ----sumlmb_out9--------------------------------------------------------------
set.seed(333)
lmb_cars9<-lmb(formula = gpm ~  c_wt+c_cyl,pfamily=dNormal(mu=pscars9$mu,Sigma=pscars9$Sigma, dispersion = pscars9$dispersion),data =mtcars)
sum_lmbcars9<-summary(lmb_cars9)
sum_lmbcars9

## ----Mt_cars_Default_Prior4---------------------------------------------------
# Use Prior_Setup to illustrate prior strength
ps4 <- Prior_Setup(
  formula = gpm ~  c_wt+c_cyl,
  family=gaussian(),
  data = mtcars,
  n_prior=1
##  ,pwt = c(0.1, 0.5),     # Example vector weights
##  priorsd = c(5, 2),     # Custom SDs for each predictor
##  priorN = NULL          # Leave NULL to focus on pwt and priorsd
)
ps4

## ----Women_Data---------------------------------------------------------------
data(women)
head(women)

## ----Women_Uncentered---------------------------------------------------------
lm_uncentered <- lm(weight ~ height, data = women)
summary(lm_uncentered)

## ----Women_Uncentered_null----------------------------------------------------
lm_uncentered_null <- lm(weight ~ 1, data = women)
#summary(lm_uncentered_null)

## ----Women_Prior_null---------------------------------------------------------
ps_null=Prior_Setup(weight ~ height,family=gaussian(),intercept_source = "null_model", effects_source = "null_effects",data=women)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion
lmb.women_null=lmb(weight ~ height,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=women,n=10000)

## ----Women_Prior_null_midpwt--------------------------------------------------
ps_null=Prior_Setup(weight ~ height,family=gaussian(),pwt=0.05,intercept_source = "null_model", effects_source = "null_effects",data=women)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion
lmb.women_null_midpwt=lmb(weight ~ height,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=women,n=10000)

## ----Women_Prior_null_hipwt---------------------------------------------------
ps_null=Prior_Setup(weight ~ height,family=gaussian(),pwt=0.5,intercept_source = "null_model", effects_source = "null_effects",data=women)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion
lmb.women_null_hipwt=lmb(weight ~ height,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=women,n=10000)

## ----Women_Prior_full---------------------------------------------------------
ps_full=Prior_Setup(weight ~ height,family=gaussian(),pwt=0.01,intercept_source = "full_model", effects_source = "full_model",data=women)
mu_full=ps_full$mu
V_full=ps_full$Sigma
disp_ML_full=ps_full$dispersion
lmb.women_full=lmb(weight ~ height,dNormal(mu_full,V_full,dispersion=disp_ML_full),data=women,n=10000)


## ----Women_Prior_full_midpwt--------------------------------------------------
ps_full=Prior_Setup(weight ~ height,family=gaussian(),pwt=0.05,intercept_source = "full_model", effects_source = "full_model",data=women)
mu_full=ps_full$mu
V_full=ps_full$Sigma
disp_ML_full=ps_full$dispersion
lmb.women_full_midpwt=lmb(weight ~ height,dNormal(mu_full,V_full,dispersion=disp_ML_full),data=women,n=10000)



## ----Women_Prior_full_hipwt---------------------------------------------------
ps_full=Prior_Setup(weight ~ height,family=gaussian(),pwt=0.5,intercept_source = "full_model", effects_source = "full_model",data=women)
mu_full=ps_full$mu
V_full=ps_full$Sigma
disp_ML_full=ps_full$dispersion
lmb.women_full_hipwt=lmb(weight ~ height,dNormal(mu_full,V_full,dispersion=disp_ML_full),data=women,n=10000)



## ----Women_Prior_default------------------------------------------------------
ps_default=Prior_Setup(weight ~ height,family=gaussian(),intercept_source = "full_model", effects_source = "null_effects",data=women)
mu_default=ps_default$mu
V_default=ps_default$Sigma
disp_ML_default=ps_default$dispersion

## ----women_lmb_call_default---------------------------------------------------
lmb.women_default=lmb(weight ~ height,dNormal(mu_default,V_default,dispersion=disp_ML_default),data=women,n=10000)

## ----Women_Prior_midpwt-------------------------------------------------------
ps_midpwt=Prior_Setup(weight ~ height,family=gaussian(),pwt=0.05,intercept_source = "full_model", effects_source = "null_effects",data=women)
mu_midpwt=ps_midpwt$mu
V_midpwt=ps_midpwt$Sigma
disp_ML_midpwt=ps_midpwt$dispersion
lmb.women_midpwt=lmb(weight ~ height,dNormal(mu_midpwt,V_midpwt,dispersion=disp_ML_midpwt),data=women,n=10000)


## ----Women_Prior_hipwt--------------------------------------------------------
ps_hipwt=Prior_Setup(weight ~ height,family=gaussian(),pwt=0.5,intercept_source = "full_model", effects_source = "null_effects",data=women)
mu_hipwt=ps_hipwt$mu
V_hipwt=ps_hipwt$Sigma
disp_ML_hipwt=ps_hipwt$dispersion
lmb.women_hipwt=lmb(weight ~ height,dNormal(mu_hipwt,V_hipwt,dispersion=disp_ML_hipwt),data=women,n=10000)


## ----Summary_Comparisons------------------------------------------------------
summary_classical <- summary(lm_uncentered)

intercept_classical <- coef(summary_classical)["(Intercept)", "Estimate"]
estimate_classical <- coef(summary_classical)["height", "Estimate"]
se_classical       <- coef(summary_classical)["height", "Std. Error"]
pr_tail_classical  <- coef(summary_classical)["height", "Pr(>|t|)"] / 2
eff_params_classical <- extractAIC(lm_uncentered)[1]
AIC_Classical <-AIC(lm_uncentered)-2

summary_classical_null <- summary(lm_uncentered_null)

intercept_classical_null <- coef(summary_classical_null)["(Intercept)", "Estimate"]
estimate_classical_null <- NA_real_
se_classical_null       <- NA_real_
pr_tail_classical_null  <- NA_real_
eff_params_classical_null <- extractAIC(lm_uncentered_null)[1]
AIC_Classical_null <-AIC(lm_uncentered_null)-2



sum_default=summary(lmb.women_default)

intercept_default <- coef(sum_default)["(Intercept)", "Post.Mean"]
estimate_default <- sum_default$coefficients["height", "Post.Mean"]
sd_default       <- sum_default$coefficients["height", "Post.Sd"]
pr_tail_default  <- sum_default$coefficients["height", "Pr(Prior_tail)"]
eff_params_default <- sum_default$pD
DIC_default <- sum_default$DIC


sum_null=summary(lmb.women_null)

intercept_null <- coef(sum_null)["(Intercept)", "Post.Mean"]
estimate_null <- sum_null$coefficients["height", "Post.Mean"]
sd_null       <- sum_null$coefficients["height", "Post.Sd"]
pr_tail_null  <- sum_null$coefficients["height", "Pr(Prior_tail)"]
eff_params_null <- sum_null$pD
DIC_null <- sum_null$DIC

sum_null_midpwt=summary(lmb.women_null_midpwt)

intercept_null_midpwt <- coef(sum_null_midpwt)["(Intercept)", "Post.Mean"]
estimate_null_midpwt <- sum_null_midpwt$coefficients["height", "Post.Mean"]
sd_null_midpwt       <- sum_null_midpwt$coefficients["height", "Post.Sd"]
pr_tail_null_midpwt  <- sum_null_midpwt$coefficients["height", "Pr(Prior_tail)"]
eff_params_null_midpwt <- sum_null_midpwt$pD
DIC_null_midpwt <- sum_null_midpwt$DIC

sum_null_hipwt=summary(lmb.women_null_hipwt)

intercept_null_hipwt <- coef(sum_null_hipwt)["(Intercept)", "Post.Mean"]
estimate_null_hipwt <- sum_null_hipwt$coefficients["height", "Post.Mean"]
sd_null_hipwt       <- sum_null_hipwt$coefficients["height", "Post.Sd"]
pr_tail_null_hipwt  <- sum_null_hipwt$coefficients["height", "Pr(Prior_tail)"]
eff_params_null_hipwt <- sum_null_hipwt$pD
DIC_null_hipwt <- sum_null_hipwt$DIC



sum_full=summary(lmb.women_full)

intercept_full <- coef(sum_full)["(Intercept)", "Post.Mean"]
estimate_full <- sum_full$coefficients["height", "Post.Mean"]
sd_full       <- sum_full$coefficients["height", "Post.Sd"]
pr_tail_full  <- sum_full$coefficients["height", "Pr(Prior_tail)"]
eff_params_full <- sum_full$pD
DIC_full <- sum_full$DIC

sum_full_midpwt=summary(lmb.women_full_midpwt)

intercept_full_midpwt <- coef(sum_full_midpwt)["(Intercept)", "Post.Mean"]
estimate_full_midpwt <- sum_full_midpwt$coefficients["height", "Post.Mean"]
sd_full_midpwt       <- sum_full_midpwt$coefficients["height", "Post.Sd"]
pr_tail_full_midpwt  <- sum_full_midpwt$coefficients["height", "Pr(Prior_tail)"]
eff_params_full_midpwt <- sum_full_midpwt$pD
DIC_full_midpwt <- sum_full_midpwt$DIC

sum_full_hipwt=summary(lmb.women_full_hipwt)

intercept_full_hipwt <- coef(sum_full_hipwt)["(Intercept)", "Post.Mean"]
estimate_full_hipwt <- sum_full_hipwt$coefficients["height", "Post.Mean"]
sd_full_hipwt       <- sum_full_hipwt$coefficients["height", "Post.Sd"]
pr_tail_full_hipwt  <- sum_full_hipwt$coefficients["height", "Pr(Prior_tail)"]
eff_params_full_hipwt <- sum_full_hipwt$pD
DIC_full_hipwt <- sum_full_hipwt$DIC


sum_midpwt=summary(lmb.women_midpwt)

intercept_midpwt <- coef(sum_midpwt)["(Intercept)", "Post.Mean"]
estimate_midpwt <- sum_midpwt$coefficients["height", "Post.Mean"]
sd_midpwt       <- sum_midpwt$coefficients["height", "Post.Sd"]
pr_tail_midpwt  <- sum_midpwt$coefficients["height", "Pr(Prior_tail)"]
eff_params_midpwt <- sum_midpwt$pD
DIC_midpwt <- sum_midpwt$DIC

sum_hipwt=summary(lmb.women_hipwt)

intercept_hipwt <- coef(sum_hipwt)["(Intercept)", "Post.Mean"]
estimate_hipwt <- sum_hipwt$coefficients["height", "Post.Mean"]
sd_hipwt       <- sum_hipwt$coefficients["height", "Post.Sd"]
pr_tail_hipwt  <- sum_hipwt$coefficients["height", "Pr(Prior_tail)"]
eff_params_hipwt <- sum_hipwt$pD
DIC_hipwt <- sum_hipwt$DIC


comparison <- data.frame(
  Model           = c("Classical LM Null","Classical LM", "Null Model Prior (pwt=0.01)","Null Model Prior (pwt=0.05)","Null Model Prior (pwt=0.5)","Full-Model Prior  (pwt=0.01)","Full-Model Prior  (pwt=0.05)","Full-Model Prior  (pwt=0.5)","Control Prior (pwt=0.01) ","Control Prior (pwt=0.05)","Control Prior (pwt=0.5)"),
  Post.Intercept_Mean        = c(intercept_classical_null,intercept_classical, intercept_null,intercept_null_midpwt,intercept_null_hipwt, intercept_full,intercept_full_midpwt,intercept_full_hipwt, intercept_default, intercept_midpwt, intercept_hipwt),
    Post.Mean        = c(estimate_classical_null,estimate_classical,  estimate_null,estimate_null_midpwt,estimate_null_hipwt, estimate_full,estimate_full_midpwt,estimate_full_hipwt, estimate_default,estimate_midpwt, estimate_hipwt),
  Post.SD        = c(se_classical_null,se_classical, sd_null,sd_null_midpwt, sd_null_hipwt,sd_full, sd_full_midpwt,sd_full_hipwt,  sd_default,sd_midpwt, sd_hipwt),
  Pr_Tail         = c(pr_tail_classical_null,pr_tail_classical,  pr_tail_null, pr_tail_null_midpwt,pr_tail_null_hipwt, pr_tail_full, pr_tail_full_midpwt,pr_tail_full_hipwt,pr_tail_default, pr_tail_midpwt, pr_tail_hipwt),
  Eff.Params      = c(eff_params_classical_null,eff_params_classical,  eff_params_null,eff_params_null_midpwt,eff_params_null_hipwt, eff_params_full,eff_params_full_midpwt,eff_params_full_hipwt, eff_params_default,eff_params_midpwt, eff_params_hipwt),
  DIC      = c(AIC_Classical_null,AIC_Classical,  DIC_null,DIC_null_midpwt, DIC_null_hipwt, DIC_full,DIC_full_midpwt,DIC_full_hipwt,DIC_default, DIC_midpwt, DIC_hipwt)
)                     
#comparison



knitr::kable(
  comparison, 
  digits  = 4,     # rounds all numeric columns to 4 decimals
  caption = "Comparison of Priors"
)

##AIC(lm_uncentered)
#residuals(lm_uncentered)

## ----half_space_tail----------------------------------------------------------

directional_half_space_tail <- function(fit,
                                               normalize = TRUE) {
  # 1. Extract posterior draws and prior moments
  post        <- fit$coefficients            # S × p matrix
  mu_prior    <- as.numeric(fit$Prior$mean)  # length-p
  V0          <- as.matrix(fit$Prior$Variance)  # p × p
  
  # 2. Compute prior precision and its symmetric square root
  P0    <- solve(V0)   # prior precision = Σ_prior^{-1}
  eig   <- eigen(P0, symmetric = TRUE)
  P0_sqrt <- eig$vectors %*% diag(sqrt(eig$values)) %*% t(eig$vectors)
  # Now P0_sqrt %*% P0_sqrt = P0
  
  # 3. Whiten draws and prior mean
  #    Z = Σ_prior^{-1/2} * (post - mu_prior)
  centered <- sweep(post, 2, mu_prior, FUN = "-")   # S × p
  Z        <- t(P0_sqrt %*% t(centered))            # S × p
  # In this whitened space the prior is N(0, I)
  
  # 4. Compute posterior mean in whitened space
  mu_post_z <- colMeans(Z)     # length-p
  delta     <- mu_post_z       # shift from zero
  
  # 5. Choose signed weights: +1 if delta>0, -1 if delta<0
  sign_vec <- sign(delta)      # length-p of ±1
  
  # 6. Raw weights (no need to divide by any SD since prior sd=1 in Z-space)
  w_raw    <- sign_vec         # length-p
  
  # 7. Optional normalization to unit length
  if (normalize) {
    w <- w_raw / sqrt(sum(w_raw^2))
  } else {
    w <- w_raw
  }
  
  # 8. Project and get reverse‐tail probability
  proj      <- Z %*% w         # S×1 vector of wᵀZ
  tail_prob <- mean(proj < 0)  # P(wᵀZ < 0)
  
  # 9. Return results
  list(
    tail_prob = as.numeric(tail_prob),
    weights   = as.numeric(w),
    proj      = as.numeric(proj),
    delta     = delta
  )
}

## ----test1--------------------------------------------------------------------

directional_half_space_tail(lmb.women_null)

## ----women_centering----------------------------------------------------------

# 1. Load the data
data(women)

# 2. Create a new column height_c = height – mean(height)
women_centered <- women
women_centered$height_c <- women_centered$height - mean(women_centered$height)

# 3. Quick check
head(women_centered)
#>   height weight height_c
#> 1     58    115     -3.5
#> 2     59    117     -2.5
#> 3     60    120     -1.5
#> 4     61    123     -0.5
#> 5     62    126      0.5
#> 6     63    129      1.5


## ----women_centered-----------------------------------------------------------

# 4. Re‐fit the linear model using centered height
lm_centered <- lm(weight ~ height_c, data = women_centered)
summary(lm_centered)

## ----women_centered_null------------------------------------------------------
lm_centered_null <- lm(weight ~ 1, data = women_centered)
summary(lm_centered_null)

## ----Women_c_Prior_null-------------------------------------------------------
ps_null=Prior_Setup(weight ~ height_c,family=gaussian(),intercept_source = "null_model", effects_source = "null_effects",data=women_centered)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion
lmb.women_null=lmb(weight ~ height_c,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=women_centered,n=10000)

## ----Women_c_Prior_null_midpwt------------------------------------------------
ps_null=Prior_Setup(weight ~ height_c,family=gaussian(),pwt=0.05,intercept_source = "null_model", effects_source = "null_effects",data=women_centered)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion
lmb.women_null_midpwt=lmb(weight ~ height_c,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=women_centered,n=10000)

## ----Women_c_Prior_null_hipwt-------------------------------------------------
ps_null=Prior_Setup(weight ~ height_c,family=gaussian(),pwt=0.5,intercept_source = "null_model", effects_source = "null_effects",data=women_centered)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion
lmb.women_null_hipwt=lmb(weight ~ height_c,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=women_centered,n=10000)

## ----Women_c_Prior_full-------------------------------------------------------
ps_full=Prior_Setup(weight ~ height_c,family=gaussian(),pwt=0.01,intercept_source = "full_model", effects_source = "full_model",data=women_centered)
mu_full=ps_full$mu
V_full=ps_full$Sigma
disp_ML_full=ps_full$dispersion
lmb.women_full=lmb(weight ~ height_c,dNormal(mu_full,V_full,dispersion=disp_ML_full),data=women_centered,n=10000)


## ----Women_c_Prior_default----------------------------------------------------
ps_default=Prior_Setup(weight ~ height_c,family=gaussian(),intercept_source = "full_model", effects_source = "null_effects",data=women_centered)
mu_default=ps_default$mu
V_default=ps_default$Sigma
disp_ML_default=ps_default$dispersion

## ----women_c_lmb_call_default-------------------------------------------------
lmb.women_default=lmb(weight ~ height_c,dNormal(mu_default,V_default,dispersion=disp_ML_default),data=women_centered,n=10000)

## ----Women_c_Prior_midpwt-----------------------------------------------------
ps_midpwt=Prior_Setup(weight ~ height_c,family=gaussian(),pwt=0.05,intercept_source = "full_model", effects_source = "null_effects",data=women_centered)
mu_midpwt=ps_midpwt$mu
V_midpwt=ps_midpwt$Sigma
disp_ML_midpwt=ps_midpwt$dispersion
lmb.women_midpwt=lmb(weight ~ height_c,dNormal(mu_midpwt,V_midpwt,dispersion=disp_ML_midpwt),data=women_centered,n=10000)


## ----Women_c_Prior_hipwt------------------------------------------------------
ps_hipwt=Prior_Setup(weight ~ height_c,family=gaussian(),pwt=0.5,intercept_source = "full_model", effects_source = "null_effects",data=women_centered)
mu_hipwt=ps_hipwt$mu
V_hipwt=ps_hipwt$Sigma
disp_ML_hipwt=ps_hipwt$dispersion
lmb.women_hipwt=lmb(weight ~ height_c,dNormal(mu_hipwt,V_hipwt,dispersion=disp_ML_hipwt),data=women_centered,n=10000)


## ----Summary_Comparisons_centered---------------------------------------------
summary_classical <- summary(lm_centered)

intercept_classical <- coef(summary_classical)["(Intercept)", "Estimate"]
estimate_classical <- coef(summary_classical)["height_c", "Estimate"]
se_classical       <- coef(summary_classical)["height_c", "Std. Error"]
pr_tail_classical  <- coef(summary_classical)["height_c", "Pr(>|t|)"] / 2
eff_params_classical <- extractAIC(lm_centered)[1]
AIC_Classical <-AIC(lm_uncentered)-2

summary_classical_null <- summary(lm_centered_null)

intercept_classical_null <- coef(summary_classical_null)["(Intercept)", "Estimate"]
estimate_classical_null <- NA_real_
se_classical_null       <- NA_real_
pr_tail_classical_null  <- NA_real_
eff_params_classical_null <- extractAIC(lm_centered_null)[1]
AIC_Classical_null <-AIC(lm_uncentered_null)-2




sum_null=summary(lmb.women_null)

intercept_null <- coef(sum_null)["(Intercept)", "Post.Mean"]
estimate_null <- sum_null$coefficients["height_c", "Post.Mean"]
sd_null       <- sum_null$coefficients["height_c", "Post.Sd"]
pr_tail_null  <- sum_null$coefficients["height_c", "Pr(Prior_tail)"]
eff_params_null <- sum_null$pD
DIC_null <- sum_null$DIC

sum_null_midpwt=summary(lmb.women_null_midpwt)

intercept_null_midpwt <- coef(sum_null_midpwt)["(Intercept)", "Post.Mean"]
estimate_null_midpwt <- sum_null_midpwt$coefficients["height_c", "Post.Mean"]
sd_null_midpwt       <- sum_null_midpwt$coefficients["height_c", "Post.Sd"]
pr_tail_null_midpwt  <- sum_null_midpwt$coefficients["height_c", "Pr(Prior_tail)"]
eff_params_null_midpwt <- sum_null_midpwt$pD
DIC_null_midpwt <- sum_null_midpwt$DIC

sum_null_hipwt=summary(lmb.women_null_hipwt)

intercept_null_hipwt <- coef(sum_null_hipwt)["(Intercept)", "Post.Mean"]
estimate_null_hipwt <- sum_null_hipwt$coefficients["height_c", "Post.Mean"]
sd_null_hipwt       <- sum_null_hipwt$coefficients["height_c", "Post.Sd"]
pr_tail_null_hipwt  <- sum_null_hipwt$coefficients["height_c", "Pr(Prior_tail)"]
eff_params_null_hipwt <- sum_null_hipwt$pD
DIC_null_hipwt <- sum_null_hipwt$DIC



sum_full=summary(lmb.women_full)

intercept_full <- coef(sum_full)["(Intercept)", "Post.Mean"]
estimate_full <- sum_full$coefficients["height_c", "Post.Mean"]
sd_full       <- sum_full$coefficients["height_c", "Post.Sd"]
pr_tail_full  <- sum_full$coefficients["height_c", "Pr(Prior_tail)"]
eff_params_full <- sum_full$pD
DIC_full <- sum_full$DIC


sum_default=summary(lmb.women_default)

intercept_default <- coef(sum_default)["(Intercept)", "Post.Mean"]
estimate_default <- sum_default$coefficients["height_c", "Post.Mean"]
sd_default       <- sum_default$coefficients["height_c", "Post.Sd"]
pr_tail_default  <- sum_default$coefficients["height_c", "Pr(Prior_tail)"]
eff_params_default <- sum_default$pD
DIC_default <- sum_default$DIC


sum_midpwt=summary(lmb.women_midpwt)

intercept_midpwt <- coef(sum_midpwt)["(Intercept)", "Post.Mean"]
estimate_midpwt <- sum_midpwt$coefficients["height_c", "Post.Mean"]
sd_midpwt       <- sum_midpwt$coefficients["height_c", "Post.Sd"]
pr_tail_midpwt  <- sum_midpwt$coefficients["height_c", "Pr(Prior_tail)"]
eff_params_midpwt <- sum_midpwt$pD
DIC_midpwt <- sum_midpwt$DIC

sum_hipwt=summary(lmb.women_hipwt)

intercept_hipwt <- coef(sum_hipwt)["(Intercept)", "Post.Mean"]
estimate_hipwt <- sum_hipwt$coefficients["height_c", "Post.Mean"]
sd_hipwt       <- sum_hipwt$coefficients["height_c", "Post.Sd"]
pr_tail_hipwt  <- sum_hipwt$coefficients["height_c", "Pr(Prior_tail)"]
eff_params_hipwt <- sum_hipwt$pD
DIC_hipwt <- sum_hipwt$DIC


comparison <- data.frame(
  Model           = c("Classical LM Null","Classical LM", "Null Model Prior (pwt=0.01)","Null Model Prior (pwt=0.05)","Null Model Prior (pwt=0.5)","Full-Model Prior  (pwt=0.01)","Control Prior (pwt=0.01) ","Control Prior (pwt=0.05)","Control Prior (pwt=0.5)"),
  Post.Intercept_Mean        = c(intercept_classical_null,intercept_classical, intercept_null,intercept_null_midpwt,intercept_null_hipwt, intercept_full, intercept_default, intercept_midpwt, intercept_hipwt),
    Post.Mean        = c(estimate_classical_null,estimate_classical,  estimate_null,estimate_null_midpwt,estimate_null_hipwt, estimate_full, estimate_default,estimate_midpwt, estimate_hipwt),
  Post.SD        = c(se_classical_null,se_classical, sd_null,sd_null_midpwt, sd_null_hipwt,sd_full,  sd_default,sd_midpwt, sd_hipwt),
  Pr_Tail         = c(pr_tail_classical_null,pr_tail_classical,  pr_tail_null, pr_tail_null_midpwt,pr_tail_null_hipwt, pr_tail_full,pr_tail_default, pr_tail_midpwt, pr_tail_hipwt),
  Eff.Params      = c(eff_params_classical_null,eff_params_classical,  eff_params_null,eff_params_null_midpwt,eff_params_null_hipwt, eff_params_full, eff_params_default,eff_params_midpwt, eff_params_hipwt),
  DIC      = c(AIC_Classical_null,AIC_Classical,  DIC_null,DIC_null_midpwt, DIC_null_hipwt, DIC_full,DIC_default, DIC_midpwt, DIC_hipwt)
)                     
#comparison



knitr::kable(
  comparison, 
  digits  = 4,     # rounds all numeric columns to 4 decimals
  caption = "Comparison of Priors"
)

##AIC(lm_uncentered)
#residuals(lm_uncentered)

## ----women_glmb_summary_default-----------------------------------------------
glmb.women_default=glmb(weight ~ height,family=gaussian(),pfamily=dNormal(mu_default,V_default,dispersion=disp_ML_default),data=women,n=10000)

summary(glmb.women_default)


## ----women_glmb_summary_null--------------------------------------------------
glmb.women_null=glmb(weight ~ height,family=gaussian(),pfamily=dNormal(mu_null,V_null,dispersion=disp_ML_null),data=women,n=10000)

summary(glmb.women_null)


## ----women_glmb_summary_full--------------------------------------------------
glmb.women_full=glmb(weight ~ height,family=gaussian(),pfamily=dNormal(mu_full,V_full,dispersion=disp_ML_full),data=women,n=10000)

summary(glmb.women_full)


## ----women_glmb_summary_lowpwt------------------------------------------------
glmb.women_lowpwt=glmb(weight ~ height,family=gaussian(),pfamily=dNormal(mu_default,V_default,dispersion=disp_ML_default),data=women,n=10000)
summary(glmb.women_lowpwt)


## ----women_glmb_call_lowpwt_null----------------------------------------------
glmb.women_lowpwt_null=glmb(weight ~ height,family=gaussian(),pfamily=dNormal(mu_null,V_default,dispersion=disp_ML_default),data=women,n=10000)
summary(glmb.women_lowpwt_null)


## ----women_glmb_call_hipwt_null-----------------------------------------------
glmb.women_hipwt_null=glmb(weight ~ height,family=gaussian(),pfamily=dNormal(mu_null,V_hipwt,dispersion=disp_ML_hipwt),data=women,n=10000)
summary(glmb.women_hipwt_null)

## ----Residual_Check-----------------------------------------------------------
#residuals(glmb.women_default)
extractAIC(glmb.women_default)


## ----Plant_Setup--------------------------------------------------------------
## Annette Dobson (1990) "An Introduction to Generalized Linear Models".
## Page 9: Plant Weight Data.
ctl    <- c(4.17, 5.58, 5.18, 6.11, 4.50, 4.61, 5.17, 4.53, 5.33, 5.14)
trt    <- c(4.81, 4.17, 4.41, 3.59, 5.87, 3.83, 6.03, 4.89, 4.32, 4.69)
group  <- gl(2, 10, 20, labels = c("Ctl", "Trt"))
weight <- c(ctl, trt)

dat <- data.frame(weight, group)
#dat2<-rbind(dat,dat,dat,dat)
dat2<-rbind(dat)

## ----Plant_lm_call_default----------------------------------------------------
lm.D9_default=lm(weight ~ group,data=dat2)

## ----Plant_lm_summary_default-------------------------------------------------
summary(lm.D9_default)

## ----Plant_Prior_null---------------------------------------------------------
ps_null=Prior_Setup(weight ~ group,family=gaussian(),pwt=0.01,intercept_source = "null_model", effects_source = "null_effects",data=dat2)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion

## ----Plant_lmb_call_null------------------------------------------------------
lmb.D9_null=lmb(weight ~ group,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=dat2,n=10000)
summary(lmb.D9_null)

## ----Plant_Prior_null_midpwt--------------------------------------------------
ps_null=Prior_Setup(weight ~ group,family=gaussian(),pwt=0.05,intercept_source = "null_model", effects_source = "null_effects",data=dat2)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion

## ----Plant_lmb_call_null_midpwt-----------------------------------------------
lmb.D9_null_midpwt=lmb(weight ~ group,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=dat2,n=10000)
summary(lmb.D9_null_midpwt)

## ----Plant_Prior_null_hipwt---------------------------------------------------
ps_null=Prior_Setup(weight ~ group,family=gaussian(),pwt=0.5,intercept_source = "null_model", effects_source = "null_effects",data=dat2)
mu_null=ps_null$mu
V_null=ps_null$Sigma
disp_ML_null=ps_null$dispersion

## ----Plant_lmb_call_null_hipwt------------------------------------------------
lmb.D9_null_hipwt=lmb(weight ~ group,dNormal(mu_null,V_null,dispersion=disp_ML_null),data=dat2,n=10000)
summary(lmb.D9_null_hipwt)

## ----Plant_Prior_full---------------------------------------------------------
ps_full=Prior_Setup(weight ~ group,family=gaussian(),pwt=0.01,intercept_source = "full_model", effects_source = "full_model",data=dat2)
mu_full=ps_full$mu
V_full=ps_full$Sigma
disp_ML_full=ps_full$dispersion

## ----Plant_lmb_call_full------------------------------------------------------
lmb.D9_full=lmb(weight ~ group,dNormal(mu_full,V_full,dispersion=disp_ML_full),data=dat2,n=10000)
summary(lmb.D9_full)

## ----Plant_Prior_full_midpwt--------------------------------------------------
ps_full=Prior_Setup(weight ~ group,family=gaussian(),pwt=0.05,intercept_source = "full_model", effects_source = "full_model",data=dat2)
mu_full=ps_full$mu
V_full=ps_full$Sigma
disp_ML_full=ps_full$dispersion

## ----Plant_lmb_call_full_midpwt-----------------------------------------------
lmb.D9_full_midpwt=lmb(weight ~ group,dNormal(mu_full,V_full,dispersion=disp_ML_full),data=dat2,n=10000)
summary(lmb.D9_full_midpwt)

## ----Plant_Prior_full_hipwt---------------------------------------------------
ps_full=Prior_Setup(weight ~ group,family=gaussian(),pwt=0.5,intercept_source = "full_model", effects_source = "full_model",data=dat2)
mu_full=ps_full$mu
V_full=ps_full$Sigma
disp_ML_full=ps_full$dispersion

## ----Plant_lmb_call_full_hipwt------------------------------------------------
lmb.D9_full_hipwt=lmb(weight ~ group,dNormal(mu_full,V_full,dispersion=disp_ML_full),data=dat2,n=10000)
summary(lmb.D9_full_hipwt)

## ----Plant_Prior_default------------------------------------------------------
ps_default=Prior_Setup(weight ~ group,family=gaussian(),pwt=0.05,intercept_source = "full_model", effects_source = "null_effects",data=dat2)
mu_default=ps_default$mu
V_default=ps_default$Sigma
disp_ML_default=ps_default$dispersion

## ----Plant_lmb_call_default---------------------------------------------------
lmb.D9_default=lmb(weight ~ group,dNormal(mu_default,V_default,dispersion=disp_ML_default),data=dat2,n=10000)

## ----Plant_lmb_summary_default------------------------------------------------
summary(lmb.D9_default)



