/* Generated by tools/generate_nmathopencl_capi.R — do not edit by hand. */

#include <R_ext/Rdynload.h>
#include <R_ext/Error.h>
#include <RcppArmadillo.h>
#include "nmathopencl.h"
#include "openclPort.h"

extern "C" {

int nmathopencl_api_version(void) {
  return 1;
}

int nmathopencl_has_opencl(void) {
  return openclPort::has_opencl() ? 1 : 0;
}

SEXP nmathopencl_bessel_i_ex_opencl(SEXP x, SEXP nu, SEXP expo, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_i_ex_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<Rcpp::NumericVector>(expo),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_i_ex_opencl failed");
  }
}

SEXP nmathopencl_bessel_i_opencl(SEXP x, SEXP nu, SEXP expo_scaled, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_i_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<Rcpp::NumericVector>(expo_scaled),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_i_opencl failed");
  }
}

SEXP nmathopencl_bessel_j_ex_opencl(SEXP x, SEXP nu, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_j_ex_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_j_ex_opencl failed");
  }
}

SEXP nmathopencl_bessel_j_opencl(SEXP x, SEXP nu, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_j_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_j_opencl failed");
  }
}

SEXP nmathopencl_bessel_k_ex_opencl(SEXP x, SEXP nu, SEXP expo, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_k_ex_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<Rcpp::NumericVector>(expo),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_k_ex_opencl failed");
  }
}

SEXP nmathopencl_bessel_k_opencl(SEXP x, SEXP nu, SEXP expo_scaled, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_k_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<Rcpp::NumericVector>(expo_scaled),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_k_opencl failed");
  }
}

SEXP nmathopencl_bessel_y_ex_opencl(SEXP x, SEXP nu, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_y_ex_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_y_ex_opencl failed");
  }
}

SEXP nmathopencl_bessel_y_opencl(SEXP x, SEXP nu, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::bessel_y_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nu),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_bessel_y_opencl failed");
  }
}

SEXP nmathopencl_beta_opencl(SEXP a, SEXP b, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::beta_opencl(
        Rcpp::as<Rcpp::NumericVector>(a),
        Rcpp::as<Rcpp::NumericVector>(b),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_beta_opencl failed");
  }
}

SEXP nmathopencl_choose_opencl(SEXP n_val, SEXP k, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::choose_opencl(
        Rcpp::as<Rcpp::NumericVector>(n_val),
        Rcpp::as<Rcpp::NumericVector>(k),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_choose_opencl failed");
  }
}

SEXP nmathopencl_dbeta_opencl(SEXP x, SEXP shape1, SEXP shape2, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dbeta_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(shape1),
        Rcpp::as<Rcpp::NumericVector>(shape2),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dbeta_opencl failed");
  }
}

SEXP nmathopencl_dbinom_opencl(SEXP x, SEXP size, SEXP prob, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dbinom_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dbinom_opencl failed");
  }
}

SEXP nmathopencl_dbinom_raw_opencl(SEXP x, SEXP n_size, SEXP prob, SEXP qprob, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dbinom_raw_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(n_size),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::NumericVector>(qprob),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dbinom_raw_opencl failed");
  }
}

SEXP nmathopencl_dcauchy_opencl(SEXP x, SEXP location, SEXP scale, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dcauchy_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(location),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dcauchy_opencl failed");
  }
}

SEXP nmathopencl_dchisq_opencl(SEXP x, SEXP df, SEXP ncp, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dchisq_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dchisq_opencl failed");
  }
}

SEXP nmathopencl_dexp_opencl(SEXP x, SEXP rate, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dexp_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(rate),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dexp_opencl failed");
  }
}

SEXP nmathopencl_df_opencl(SEXP x, SEXP df1, SEXP df2, SEXP ncp, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::df_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(df1),
        Rcpp::as<Rcpp::NumericVector>(df2),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_df_opencl failed");
  }
}

SEXP nmathopencl_dgamma_opencl(SEXP x, SEXP shape, SEXP scale, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dgamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(shape),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dgamma_opencl failed");
  }
}

SEXP nmathopencl_dgeom_opencl(SEXP x, SEXP prob, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dgeom_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dgeom_opencl failed");
  }
}

SEXP nmathopencl_dhyper_opencl(SEXP x, SEXP r, SEXP b, SEXP n1, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dhyper_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(r),
        Rcpp::as<Rcpp::NumericVector>(b),
        Rcpp::as<Rcpp::NumericVector>(n1),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dhyper_opencl failed");
  }
}

SEXP nmathopencl_digamma_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::digamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_digamma_opencl failed");
  }
}

SEXP nmathopencl_dlnorm_opencl(SEXP x, SEXP meanlog, SEXP sdlog, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dlnorm_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(meanlog),
        Rcpp::as<Rcpp::NumericVector>(sdlog),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dlnorm_opencl failed");
  }
}

SEXP nmathopencl_dlogis_opencl(SEXP x, SEXP location, SEXP scale, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dlogis_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(location),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dlogis_opencl failed");
  }
}

SEXP nmathopencl_dnbeta_opencl(SEXP x, SEXP shape1, SEXP shape2, SEXP ncp, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dnbeta_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(shape1),
        Rcpp::as<Rcpp::NumericVector>(shape2),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dnbeta_opencl failed");
  }
}

SEXP nmathopencl_dnbinom_mu_opencl(SEXP x, SEXP size, SEXP mu, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dnbinom_mu_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(mu),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dnbinom_mu_opencl failed");
  }
}

SEXP nmathopencl_dnbinom_opencl(SEXP x, SEXP size, SEXP prob, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dnbinom_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dnbinom_opencl failed");
  }
}

SEXP nmathopencl_dnorm_opencl(SEXP x, SEXP mean, SEXP sd, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dnorm_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(mean),
        Rcpp::as<Rcpp::NumericVector>(sd),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dnorm_opencl failed");
  }
}

SEXP nmathopencl_dpois_opencl(SEXP x, SEXP lambda, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dpois_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(lambda),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dpois_opencl failed");
  }
}

SEXP nmathopencl_dpois_raw_opencl(SEXP x, SEXP lambda, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dpois_raw_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(lambda),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dpois_raw_opencl failed");
  }
}

SEXP nmathopencl_dpsifn_opencl(SEXP x, SEXP n_deriv, SEXP kode, SEXP m, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dpsifn_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(n_deriv),
        Rcpp::as<Rcpp::NumericVector>(kode),
        Rcpp::as<Rcpp::NumericVector>(m),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dpsifn_opencl failed");
  }
}

SEXP nmathopencl_dsignrank_opencl(SEXP x, SEXP nsize, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dsignrank_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(nsize),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dsignrank_opencl failed");
  }
}

SEXP nmathopencl_dt_opencl(SEXP x, SEXP df, SEXP ncp, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dt_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dt_opencl failed");
  }
}

SEXP nmathopencl_dunif_opencl(SEXP x, SEXP min, SEXP max, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dunif_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(min),
        Rcpp::as<Rcpp::NumericVector>(max),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dunif_opencl failed");
  }
}

SEXP nmathopencl_dweibull_opencl(SEXP x, SEXP shape, SEXP scale, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dweibull_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(shape),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dweibull_opencl failed");
  }
}

SEXP nmathopencl_dwilcox_opencl(SEXP x, SEXP m, SEXP n2, SEXP give_log, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::dwilcox_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(m),
        Rcpp::as<Rcpp::NumericVector>(n2),
        Rcpp::as<Rcpp::IntegerVector>(give_log),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_dwilcox_opencl failed");
  }
}

SEXP nmathopencl_exp_rand_opencl(SEXP n, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::exp_rand_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_exp_rand_opencl failed");
  }
}

SEXP nmathopencl_fmax2_opencl(SEXP x, SEXP y, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::fmax2_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(y),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_fmax2_opencl failed");
  }
}

SEXP nmathopencl_fmin2_opencl(SEXP x, SEXP y, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::fmin2_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(y),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_fmin2_opencl failed");
  }
}

SEXP nmathopencl_fprec_opencl(SEXP x, SEXP digits, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::fprec_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(digits),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_fprec_opencl failed");
  }
}

SEXP nmathopencl_fround_opencl(SEXP x, SEXP digits, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::fround_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(digits),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_fround_opencl failed");
  }
}

SEXP nmathopencl_fsign_opencl(SEXP x, SEXP y, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::fsign_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(y),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_fsign_opencl failed");
  }
}

SEXP nmathopencl_ftrunc_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::ftrunc_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_ftrunc_opencl failed");
  }
}

SEXP nmathopencl_gammafn_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::gammafn_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_gammafn_opencl failed");
  }
}

SEXP nmathopencl_imax2_opencl(SEXP x, SEXP y, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::imax2_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(y),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_imax2_opencl failed");
  }
}

SEXP nmathopencl_imin2_opencl(SEXP x, SEXP y, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::imin2_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(y),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_imin2_opencl failed");
  }
}

SEXP nmathopencl_lbeta_opencl(SEXP a, SEXP b, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::lbeta_opencl(
        Rcpp::as<Rcpp::NumericVector>(a),
        Rcpp::as<Rcpp::NumericVector>(b),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_lbeta_opencl failed");
  }
}

SEXP nmathopencl_lchoose_opencl(SEXP n_val, SEXP k, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::lchoose_opencl(
        Rcpp::as<Rcpp::NumericVector>(n_val),
        Rcpp::as<Rcpp::NumericVector>(k),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_lchoose_opencl failed");
  }
}

SEXP nmathopencl_lgamma1p_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::lgamma1p_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_lgamma1p_opencl failed");
  }
}

SEXP nmathopencl_lgammafn_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::lgammafn_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_lgammafn_opencl failed");
  }
}

SEXP nmathopencl_lgammafn_sign_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::lgammafn_sign_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_lgammafn_sign_opencl failed");
  }
}

SEXP nmathopencl_log1mexp_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::log1mexp_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_log1mexp_opencl failed");
  }
}

SEXP nmathopencl_log1pexp_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::log1pexp_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_log1pexp_opencl failed");
  }
}

SEXP nmathopencl_log1pmx_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::log1pmx_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_log1pmx_opencl failed");
  }
}

SEXP nmathopencl_logspace_add_opencl(SEXP logx, SEXP logy, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::logspace_add_opencl(
        Rcpp::as<Rcpp::NumericVector>(logx),
        Rcpp::as<Rcpp::NumericVector>(logy),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_logspace_add_opencl failed");
  }
}

SEXP nmathopencl_logspace_sub_opencl(SEXP logx, SEXP logy, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::logspace_sub_opencl(
        Rcpp::as<Rcpp::NumericVector>(logx),
        Rcpp::as<Rcpp::NumericVector>(logy),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_logspace_sub_opencl failed");
  }
}

SEXP nmathopencl_logspace_sum_opencl(SEXP logx, SEXP logy, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::logspace_sum_opencl(
        Rcpp::as<Rcpp::NumericVector>(logx),
        Rcpp::as<Rcpp::NumericVector>(logy),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_logspace_sum_opencl failed");
  }
}

SEXP nmathopencl_norm_rand_opencl(SEXP n, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::norm_rand_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_norm_rand_opencl failed");
  }
}

SEXP nmathopencl_pbeta_opencl(SEXP q, SEXP shape1, SEXP shape2, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pbeta_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(shape1),
        Rcpp::as<Rcpp::NumericVector>(shape2),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pbeta_opencl failed");
  }
}

SEXP nmathopencl_pbinom_opencl(SEXP q, SEXP size, SEXP prob, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pbinom_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pbinom_opencl failed");
  }
}

SEXP nmathopencl_pcauchy_opencl(SEXP q, SEXP location, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pcauchy_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(location),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pcauchy_opencl failed");
  }
}

SEXP nmathopencl_pchisq_opencl(SEXP q, SEXP df, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pchisq_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pchisq_opencl failed");
  }
}

SEXP nmathopencl_pentagamma_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pentagamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pentagamma_opencl failed");
  }
}

SEXP nmathopencl_pexp_opencl(SEXP q, SEXP rate, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pexp_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(rate),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pexp_opencl failed");
  }
}

SEXP nmathopencl_pf_opencl(SEXP q, SEXP df1, SEXP df2, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pf_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(df1),
        Rcpp::as<Rcpp::NumericVector>(df2),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pf_opencl failed");
  }
}

SEXP nmathopencl_pgamma_opencl(SEXP q, SEXP shape, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pgamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(shape),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pgamma_opencl failed");
  }
}

SEXP nmathopencl_pgeom_opencl(SEXP q, SEXP prob, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pgeom_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pgeom_opencl failed");
  }
}

SEXP nmathopencl_phyper_opencl(SEXP q, SEXP m, SEXP n_black, SEXP k, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::phyper_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(m),
        Rcpp::as<Rcpp::NumericVector>(n_black),
        Rcpp::as<Rcpp::NumericVector>(k),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_phyper_opencl failed");
  }
}

SEXP nmathopencl_plnorm_opencl(SEXP q, SEXP meanlog, SEXP sdlog, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::plnorm_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(meanlog),
        Rcpp::as<Rcpp::NumericVector>(sdlog),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_plnorm_opencl failed");
  }
}

SEXP nmathopencl_plogis_opencl(SEXP q, SEXP location, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::plogis_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(location),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_plogis_opencl failed");
  }
}

SEXP nmathopencl_pnbinom_mu_opencl(SEXP q, SEXP size, SEXP mu, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pnbinom_mu_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(mu),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pnbinom_mu_opencl failed");
  }
}

SEXP nmathopencl_pnbinom_opencl(SEXP q, SEXP size, SEXP prob, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pnbinom_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pnbinom_opencl failed");
  }
}

SEXP nmathopencl_pnorm_opencl(SEXP q, SEXP mean, SEXP sd, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pnorm_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(mean),
        Rcpp::as<Rcpp::NumericVector>(sd),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pnorm_opencl failed");
  }
}

SEXP nmathopencl_pow1p_opencl(SEXP x, SEXP y, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pow1p_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(y),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pow1p_opencl failed");
  }
}

SEXP nmathopencl_ppois_opencl(SEXP q, SEXP lambda, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::ppois_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(lambda),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_ppois_opencl failed");
  }
}

SEXP nmathopencl_psigamma_opencl(SEXP x, SEXP deriv, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::psigamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(deriv),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_psigamma_opencl failed");
  }
}

SEXP nmathopencl_psignrank_opencl(SEXP q, SEXP nsize, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::psignrank_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(nsize),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_psignrank_opencl failed");
  }
}

SEXP nmathopencl_pt_opencl(SEXP q, SEXP df, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pt_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pt_opencl failed");
  }
}

SEXP nmathopencl_ptukey_opencl(SEXP q, SEXP nmeans, SEXP df, SEXP nranges, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::ptukey_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(nmeans),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(nranges),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_ptukey_opencl failed");
  }
}

SEXP nmathopencl_punif_opencl(SEXP q, SEXP min, SEXP max, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::punif_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(min),
        Rcpp::as<Rcpp::NumericVector>(max),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_punif_opencl failed");
  }
}

SEXP nmathopencl_pweibull_opencl(SEXP q, SEXP shape, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pweibull_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(shape),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pweibull_opencl failed");
  }
}

SEXP nmathopencl_pwilcox_opencl(SEXP q, SEXP m, SEXP n2, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::pwilcox_opencl(
        Rcpp::as<Rcpp::NumericVector>(q),
        Rcpp::as<Rcpp::NumericVector>(m),
        Rcpp::as<Rcpp::NumericVector>(n2),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_pwilcox_opencl failed");
  }
}

SEXP nmathopencl_qbeta_opencl(SEXP p, SEXP shape1, SEXP shape2, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qbeta_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(shape1),
        Rcpp::as<Rcpp::NumericVector>(shape2),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qbeta_opencl failed");
  }
}

SEXP nmathopencl_qbinom_opencl(SEXP p, SEXP size, SEXP prob, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qbinom_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qbinom_opencl failed");
  }
}

SEXP nmathopencl_qcauchy_opencl(SEXP p, SEXP location, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qcauchy_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(location),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qcauchy_opencl failed");
  }
}

SEXP nmathopencl_qchisq_opencl(SEXP p, SEXP df, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qchisq_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qchisq_opencl failed");
  }
}

SEXP nmathopencl_qexp_opencl(SEXP p, SEXP rate, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qexp_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(rate),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qexp_opencl failed");
  }
}

SEXP nmathopencl_qf_opencl(SEXP p, SEXP df1, SEXP df2, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qf_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(df1),
        Rcpp::as<Rcpp::NumericVector>(df2),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qf_opencl failed");
  }
}

SEXP nmathopencl_qgamma_opencl(SEXP p, SEXP shape, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qgamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(shape),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qgamma_opencl failed");
  }
}

SEXP nmathopencl_qgeom_opencl(SEXP p, SEXP prob, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qgeom_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qgeom_opencl failed");
  }
}

SEXP nmathopencl_qhyper_opencl(SEXP p, SEXP r, SEXP b, SEXP n1, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qhyper_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(r),
        Rcpp::as<Rcpp::NumericVector>(b),
        Rcpp::as<Rcpp::NumericVector>(n1),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qhyper_opencl failed");
  }
}

SEXP nmathopencl_qlnorm_opencl(SEXP p, SEXP meanlog, SEXP sdlog, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qlnorm_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(meanlog),
        Rcpp::as<Rcpp::NumericVector>(sdlog),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qlnorm_opencl failed");
  }
}

SEXP nmathopencl_qlogis_opencl(SEXP p, SEXP location, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qlogis_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(location),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qlogis_opencl failed");
  }
}

SEXP nmathopencl_qnbinom_mu_opencl(SEXP p, SEXP size, SEXP mu, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qnbinom_mu_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(mu),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qnbinom_mu_opencl failed");
  }
}

SEXP nmathopencl_qnbinom_opencl(SEXP p, SEXP size, SEXP prob, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qnbinom_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(size),
        Rcpp::as<Rcpp::NumericVector>(prob),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qnbinom_opencl failed");
  }
}

SEXP nmathopencl_qnorm_opencl(SEXP p, SEXP mean, SEXP sd, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qnorm_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(mean),
        Rcpp::as<Rcpp::NumericVector>(sd),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qnorm_opencl failed");
  }
}

SEXP nmathopencl_qpois_opencl(SEXP p, SEXP lambda, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qpois_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(lambda),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qpois_opencl failed");
  }
}

SEXP nmathopencl_qsignrank_opencl(SEXP p, SEXP nsize, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qsignrank_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(nsize),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qsignrank_opencl failed");
  }
}

SEXP nmathopencl_qt_opencl(SEXP p, SEXP df, SEXP ncp, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qt_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(ncp),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qt_opencl failed");
  }
}

SEXP nmathopencl_qtukey_opencl(SEXP p, SEXP nmeans, SEXP df, SEXP nranges, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qtukey_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(nmeans),
        Rcpp::as<Rcpp::NumericVector>(df),
        Rcpp::as<Rcpp::NumericVector>(nranges),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qtukey_opencl failed");
  }
}

SEXP nmathopencl_qunif_opencl(SEXP p, SEXP min, SEXP max, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qunif_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(min),
        Rcpp::as<Rcpp::NumericVector>(max),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qunif_opencl failed");
  }
}

SEXP nmathopencl_qweibull_opencl(SEXP p, SEXP shape, SEXP scale, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qweibull_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(shape),
        Rcpp::as<Rcpp::NumericVector>(scale),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qweibull_opencl failed");
  }
}

SEXP nmathopencl_qwilcox_opencl(SEXP p, SEXP m, SEXP n2, SEXP lower_tail, SEXP log_p, SEXP opencl_parallel_code, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::qwilcox_opencl(
        Rcpp::as<Rcpp::NumericVector>(p),
        Rcpp::as<Rcpp::NumericVector>(m),
        Rcpp::as<Rcpp::NumericVector>(n2),
        Rcpp::as<Rcpp::IntegerVector>(lower_tail),
        Rcpp::as<Rcpp::IntegerVector>(log_p),
        Rcpp::as<int>(opencl_parallel_code),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_qwilcox_opencl failed");
  }
}

SEXP nmathopencl_r_check_stack_opencl(SEXP n, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::r_check_stack_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_r_check_stack_opencl failed");
  }
}

SEXP nmathopencl_r_check_user_interrupt_opencl(SEXP n, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::r_check_user_interrupt_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_r_check_user_interrupt_opencl failed");
  }
}

SEXP nmathopencl_r_pow_di_opencl(SEXP x, SEXP n_exp, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::r_pow_di_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::IntegerVector>(n_exp),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_r_pow_di_opencl failed");
  }
}

SEXP nmathopencl_r_pow_opencl(SEXP x, SEXP y, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::r_pow_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<Rcpp::NumericVector>(y),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_r_pow_opencl failed");
  }
}

SEXP nmathopencl_r_unif_index_opencl(SEXP n, SEXP dn, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::r_unif_index_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(dn),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_r_unif_index_opencl failed");
  }
}

SEXP nmathopencl_rbeta_opencl(SEXP n, SEXP a, SEXP b, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rbeta_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(a),
        Rcpp::as<double>(b),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rbeta_opencl failed");
  }
}

SEXP nmathopencl_rbinom_opencl(SEXP n, SEXP size, SEXP prob, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rbinom_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(size),
        Rcpp::as<double>(prob),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rbinom_opencl failed");
  }
}

SEXP nmathopencl_rcauchy_opencl(SEXP n, SEXP location, SEXP scale, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rcauchy_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(location),
        Rcpp::as<double>(scale),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rcauchy_opencl failed");
  }
}

SEXP nmathopencl_rchisq_opencl(SEXP n, SEXP df, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rchisq_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(df),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rchisq_opencl failed");
  }
}

SEXP nmathopencl_rexp_opencl(SEXP n, SEXP scale, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rexp_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(scale),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rexp_opencl failed");
  }
}

SEXP nmathopencl_rf_opencl(SEXP n, SEXP df1, SEXP df2, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rf_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(df1),
        Rcpp::as<double>(df2),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rf_opencl failed");
  }
}

SEXP nmathopencl_rgamma_opencl(SEXP n, SEXP shape, SEXP scale, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rgamma_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(shape),
        Rcpp::as<double>(scale),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rgamma_opencl failed");
  }
}

SEXP nmathopencl_rgeom_opencl(SEXP n, SEXP prob, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rgeom_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(prob),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rgeom_opencl failed");
  }
}

SEXP nmathopencl_rhyper_opencl(SEXP n, SEXP r, SEXP b, SEXP n1, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rhyper_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(r),
        Rcpp::as<double>(b),
        Rcpp::as<double>(n1),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rhyper_opencl failed");
  }
}

SEXP nmathopencl_rlnorm_opencl(SEXP n, SEXP meanlog, SEXP sdlog, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rlnorm_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(meanlog),
        Rcpp::as<double>(sdlog),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rlnorm_opencl failed");
  }
}

SEXP nmathopencl_rlogis_opencl(SEXP n, SEXP location, SEXP scale, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rlogis_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(location),
        Rcpp::as<double>(scale),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rlogis_opencl failed");
  }
}

SEXP nmathopencl_rmultinom_opencl(SEXP n, SEXP size, SEXP prob, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rmultinom_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(size),
        Rcpp::as<double>(prob),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rmultinom_opencl failed");
  }
}

SEXP nmathopencl_rnbinom_mu_opencl(SEXP n, SEXP size, SEXP mu, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rnbinom_mu_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(size),
        Rcpp::as<double>(mu),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rnbinom_mu_opencl failed");
  }
}

SEXP nmathopencl_rnbinom_opencl(SEXP n, SEXP size, SEXP prob, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rnbinom_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(size),
        Rcpp::as<double>(prob),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rnbinom_opencl failed");
  }
}

SEXP nmathopencl_rnchisq_opencl(SEXP n, SEXP df, SEXP ncp, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rnchisq_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(df),
        Rcpp::as<double>(ncp),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rnchisq_opencl failed");
  }
}

SEXP nmathopencl_rnorm_opencl(SEXP n, SEXP mu, SEXP sigma, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rnorm_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(mu),
        Rcpp::as<double>(sigma),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rnorm_opencl failed");
  }
}

SEXP nmathopencl_rpois_opencl(SEXP n, SEXP lambda, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rpois_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(lambda),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rpois_opencl failed");
  }
}

SEXP nmathopencl_rsignrank_opencl(SEXP n, SEXP nsize, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rsignrank_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(nsize),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rsignrank_opencl failed");
  }
}

SEXP nmathopencl_rt_opencl(SEXP n, SEXP df, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rt_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(df),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rt_opencl failed");
  }
}

SEXP nmathopencl_runif_opencl(SEXP n, SEXP a, SEXP b, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::runif_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(a),
        Rcpp::as<double>(b),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_runif_opencl failed");
  }
}

SEXP nmathopencl_rweibull_opencl(SEXP n, SEXP shape, SEXP scale, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rweibull_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(shape),
        Rcpp::as<double>(scale),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rweibull_opencl failed");
  }
}

SEXP nmathopencl_rwilcox_opencl(SEXP n, SEXP m, SEXP n2, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::rwilcox_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<double>(m),
        Rcpp::as<double>(n2),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_rwilcox_opencl failed");
  }
}

SEXP nmathopencl_sign_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::sign_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_sign_opencl failed");
  }
}

SEXP nmathopencl_tetragamma_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::tetragamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_tetragamma_opencl failed");
  }
}

SEXP nmathopencl_trigamma_opencl(SEXP x, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::trigamma_opencl(
        Rcpp::as<Rcpp::NumericVector>(x),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_trigamma_opencl failed");
  }
}

SEXP nmathopencl_unif_rand_opencl(SEXP n, SEXP verbose) {
  try {
    return Rcpp::wrap(nmathopencl::unif_rand_opencl(
        Rcpp::as<int>(n),
        Rcpp::as<bool>(verbose)
    ));
  } catch (const std::exception& e) {
    Rf_error("%s", e.what());
  } catch (...) {
    Rf_error("nmathopencl_unif_rand_opencl failed");
  }
}

} // extern "C"


// [[Rcpp::export]]
void register_nmathopencl_ccallables_cpp_export() {
  R_RegisterCCallable("nmathopencl", "nmathopencl_api_version",
      (DL_FUNC) &nmathopencl_api_version);
  R_RegisterCCallable("nmathopencl", "nmathopencl_has_opencl",
      (DL_FUNC) &nmathopencl_has_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_i_ex_opencl",
      (DL_FUNC) &nmathopencl_bessel_i_ex_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_i_opencl",
      (DL_FUNC) &nmathopencl_bessel_i_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_j_ex_opencl",
      (DL_FUNC) &nmathopencl_bessel_j_ex_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_j_opencl",
      (DL_FUNC) &nmathopencl_bessel_j_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_k_ex_opencl",
      (DL_FUNC) &nmathopencl_bessel_k_ex_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_k_opencl",
      (DL_FUNC) &nmathopencl_bessel_k_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_y_ex_opencl",
      (DL_FUNC) &nmathopencl_bessel_y_ex_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_bessel_y_opencl",
      (DL_FUNC) &nmathopencl_bessel_y_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_beta_opencl",
      (DL_FUNC) &nmathopencl_beta_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_choose_opencl",
      (DL_FUNC) &nmathopencl_choose_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dbeta_opencl",
      (DL_FUNC) &nmathopencl_dbeta_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dbinom_opencl",
      (DL_FUNC) &nmathopencl_dbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dbinom_raw_opencl",
      (DL_FUNC) &nmathopencl_dbinom_raw_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dcauchy_opencl",
      (DL_FUNC) &nmathopencl_dcauchy_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dchisq_opencl",
      (DL_FUNC) &nmathopencl_dchisq_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dexp_opencl",
      (DL_FUNC) &nmathopencl_dexp_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_df_opencl",
      (DL_FUNC) &nmathopencl_df_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dgamma_opencl",
      (DL_FUNC) &nmathopencl_dgamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dgeom_opencl",
      (DL_FUNC) &nmathopencl_dgeom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dhyper_opencl",
      (DL_FUNC) &nmathopencl_dhyper_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_digamma_opencl",
      (DL_FUNC) &nmathopencl_digamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dlnorm_opencl",
      (DL_FUNC) &nmathopencl_dlnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dlogis_opencl",
      (DL_FUNC) &nmathopencl_dlogis_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dnbeta_opencl",
      (DL_FUNC) &nmathopencl_dnbeta_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dnbinom_mu_opencl",
      (DL_FUNC) &nmathopencl_dnbinom_mu_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dnbinom_opencl",
      (DL_FUNC) &nmathopencl_dnbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dnorm_opencl",
      (DL_FUNC) &nmathopencl_dnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dpois_opencl",
      (DL_FUNC) &nmathopencl_dpois_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dpois_raw_opencl",
      (DL_FUNC) &nmathopencl_dpois_raw_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dpsifn_opencl",
      (DL_FUNC) &nmathopencl_dpsifn_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dsignrank_opencl",
      (DL_FUNC) &nmathopencl_dsignrank_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dt_opencl",
      (DL_FUNC) &nmathopencl_dt_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dunif_opencl",
      (DL_FUNC) &nmathopencl_dunif_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dweibull_opencl",
      (DL_FUNC) &nmathopencl_dweibull_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_dwilcox_opencl",
      (DL_FUNC) &nmathopencl_dwilcox_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_exp_rand_opencl",
      (DL_FUNC) &nmathopencl_exp_rand_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_fmax2_opencl",
      (DL_FUNC) &nmathopencl_fmax2_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_fmin2_opencl",
      (DL_FUNC) &nmathopencl_fmin2_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_fprec_opencl",
      (DL_FUNC) &nmathopencl_fprec_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_fround_opencl",
      (DL_FUNC) &nmathopencl_fround_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_fsign_opencl",
      (DL_FUNC) &nmathopencl_fsign_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_ftrunc_opencl",
      (DL_FUNC) &nmathopencl_ftrunc_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_gammafn_opencl",
      (DL_FUNC) &nmathopencl_gammafn_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_imax2_opencl",
      (DL_FUNC) &nmathopencl_imax2_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_imin2_opencl",
      (DL_FUNC) &nmathopencl_imin2_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_lbeta_opencl",
      (DL_FUNC) &nmathopencl_lbeta_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_lchoose_opencl",
      (DL_FUNC) &nmathopencl_lchoose_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_lgamma1p_opencl",
      (DL_FUNC) &nmathopencl_lgamma1p_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_lgammafn_opencl",
      (DL_FUNC) &nmathopencl_lgammafn_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_lgammafn_sign_opencl",
      (DL_FUNC) &nmathopencl_lgammafn_sign_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_log1mexp_opencl",
      (DL_FUNC) &nmathopencl_log1mexp_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_log1pexp_opencl",
      (DL_FUNC) &nmathopencl_log1pexp_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_log1pmx_opencl",
      (DL_FUNC) &nmathopencl_log1pmx_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_logspace_add_opencl",
      (DL_FUNC) &nmathopencl_logspace_add_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_logspace_sub_opencl",
      (DL_FUNC) &nmathopencl_logspace_sub_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_logspace_sum_opencl",
      (DL_FUNC) &nmathopencl_logspace_sum_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_norm_rand_opencl",
      (DL_FUNC) &nmathopencl_norm_rand_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pbeta_opencl",
      (DL_FUNC) &nmathopencl_pbeta_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pbinom_opencl",
      (DL_FUNC) &nmathopencl_pbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pcauchy_opencl",
      (DL_FUNC) &nmathopencl_pcauchy_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pchisq_opencl",
      (DL_FUNC) &nmathopencl_pchisq_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pentagamma_opencl",
      (DL_FUNC) &nmathopencl_pentagamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pexp_opencl",
      (DL_FUNC) &nmathopencl_pexp_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pf_opencl",
      (DL_FUNC) &nmathopencl_pf_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pgamma_opencl",
      (DL_FUNC) &nmathopencl_pgamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pgeom_opencl",
      (DL_FUNC) &nmathopencl_pgeom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_phyper_opencl",
      (DL_FUNC) &nmathopencl_phyper_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_plnorm_opencl",
      (DL_FUNC) &nmathopencl_plnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_plogis_opencl",
      (DL_FUNC) &nmathopencl_plogis_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pnbinom_mu_opencl",
      (DL_FUNC) &nmathopencl_pnbinom_mu_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pnbinom_opencl",
      (DL_FUNC) &nmathopencl_pnbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pnorm_opencl",
      (DL_FUNC) &nmathopencl_pnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pow1p_opencl",
      (DL_FUNC) &nmathopencl_pow1p_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_ppois_opencl",
      (DL_FUNC) &nmathopencl_ppois_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_psigamma_opencl",
      (DL_FUNC) &nmathopencl_psigamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_psignrank_opencl",
      (DL_FUNC) &nmathopencl_psignrank_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pt_opencl",
      (DL_FUNC) &nmathopencl_pt_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_ptukey_opencl",
      (DL_FUNC) &nmathopencl_ptukey_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_punif_opencl",
      (DL_FUNC) &nmathopencl_punif_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pweibull_opencl",
      (DL_FUNC) &nmathopencl_pweibull_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_pwilcox_opencl",
      (DL_FUNC) &nmathopencl_pwilcox_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qbeta_opencl",
      (DL_FUNC) &nmathopencl_qbeta_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qbinom_opencl",
      (DL_FUNC) &nmathopencl_qbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qcauchy_opencl",
      (DL_FUNC) &nmathopencl_qcauchy_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qchisq_opencl",
      (DL_FUNC) &nmathopencl_qchisq_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qexp_opencl",
      (DL_FUNC) &nmathopencl_qexp_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qf_opencl",
      (DL_FUNC) &nmathopencl_qf_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qgamma_opencl",
      (DL_FUNC) &nmathopencl_qgamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qgeom_opencl",
      (DL_FUNC) &nmathopencl_qgeom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qhyper_opencl",
      (DL_FUNC) &nmathopencl_qhyper_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qlnorm_opencl",
      (DL_FUNC) &nmathopencl_qlnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qlogis_opencl",
      (DL_FUNC) &nmathopencl_qlogis_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qnbinom_mu_opencl",
      (DL_FUNC) &nmathopencl_qnbinom_mu_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qnbinom_opencl",
      (DL_FUNC) &nmathopencl_qnbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qnorm_opencl",
      (DL_FUNC) &nmathopencl_qnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qpois_opencl",
      (DL_FUNC) &nmathopencl_qpois_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qsignrank_opencl",
      (DL_FUNC) &nmathopencl_qsignrank_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qt_opencl",
      (DL_FUNC) &nmathopencl_qt_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qtukey_opencl",
      (DL_FUNC) &nmathopencl_qtukey_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qunif_opencl",
      (DL_FUNC) &nmathopencl_qunif_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qweibull_opencl",
      (DL_FUNC) &nmathopencl_qweibull_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_qwilcox_opencl",
      (DL_FUNC) &nmathopencl_qwilcox_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_r_check_stack_opencl",
      (DL_FUNC) &nmathopencl_r_check_stack_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_r_check_user_interrupt_opencl",
      (DL_FUNC) &nmathopencl_r_check_user_interrupt_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_r_pow_di_opencl",
      (DL_FUNC) &nmathopencl_r_pow_di_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_r_pow_opencl",
      (DL_FUNC) &nmathopencl_r_pow_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_r_unif_index_opencl",
      (DL_FUNC) &nmathopencl_r_unif_index_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rbeta_opencl",
      (DL_FUNC) &nmathopencl_rbeta_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rbinom_opencl",
      (DL_FUNC) &nmathopencl_rbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rcauchy_opencl",
      (DL_FUNC) &nmathopencl_rcauchy_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rchisq_opencl",
      (DL_FUNC) &nmathopencl_rchisq_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rexp_opencl",
      (DL_FUNC) &nmathopencl_rexp_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rf_opencl",
      (DL_FUNC) &nmathopencl_rf_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rgamma_opencl",
      (DL_FUNC) &nmathopencl_rgamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rgeom_opencl",
      (DL_FUNC) &nmathopencl_rgeom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rhyper_opencl",
      (DL_FUNC) &nmathopencl_rhyper_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rlnorm_opencl",
      (DL_FUNC) &nmathopencl_rlnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rlogis_opencl",
      (DL_FUNC) &nmathopencl_rlogis_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rmultinom_opencl",
      (DL_FUNC) &nmathopencl_rmultinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rnbinom_mu_opencl",
      (DL_FUNC) &nmathopencl_rnbinom_mu_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rnbinom_opencl",
      (DL_FUNC) &nmathopencl_rnbinom_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rnchisq_opencl",
      (DL_FUNC) &nmathopencl_rnchisq_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rnorm_opencl",
      (DL_FUNC) &nmathopencl_rnorm_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rpois_opencl",
      (DL_FUNC) &nmathopencl_rpois_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rsignrank_opencl",
      (DL_FUNC) &nmathopencl_rsignrank_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rt_opencl",
      (DL_FUNC) &nmathopencl_rt_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_runif_opencl",
      (DL_FUNC) &nmathopencl_runif_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rweibull_opencl",
      (DL_FUNC) &nmathopencl_rweibull_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_rwilcox_opencl",
      (DL_FUNC) &nmathopencl_rwilcox_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_sign_opencl",
      (DL_FUNC) &nmathopencl_sign_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_tetragamma_opencl",
      (DL_FUNC) &nmathopencl_tetragamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_trigamma_opencl",
      (DL_FUNC) &nmathopencl_trigamma_opencl);
  R_RegisterCCallable("nmathopencl", "nmathopencl_unif_rand_opencl",
      (DL_FUNC) &nmathopencl_unif_rand_opencl);
}

