# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EnvelopeSize_cpp_export <- function(a, G1, Gridtype, n, n_envopt, use_opencl, verbose) {
    .Call(`_nmathopencl_EnvelopeSize_cpp_export`, a, G1, Gridtype, n, n_envopt, use_opencl, verbose)
}

EnvelopeEval_cpp_export <- function(G4, y, x, mu, P, alpha, wt, family, link, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_nmathopencl_EnvelopeEval_cpp_export`, G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose)
}

glmb_Standardize_Model_cpp_export <- function(y, x, P, bstar, A1) {
    .Call(`_nmathopencl_glmb_Standardize_Model_cpp_export`, y, x, P, bstar, A1)
}

dnorm_opencl_cpp_export <- function(x, mu = 0.0, sigma = 1.0, give_log = FALSE, verbose = FALSE) {
    .Call(`_nmathopencl_dnorm_opencl_cpp_export`, x, mu, sigma, give_log, verbose)
}

runif_opencl_cpp_export <- function(n, a = 0.0, b = 1.0, verbose = FALSE) {
    .Call(`_nmathopencl_runif_opencl_cpp_export`, n, a, b, verbose)
}

rnorm_opencl_cpp_export <- function(n, mu = 0.0, sigma = 1.0, verbose = FALSE) {
    .Call(`_nmathopencl_rnorm_opencl_cpp_export`, n, mu, sigma, verbose)
}

rexp_opencl_cpp_export <- function(n, scale = 1.0, verbose = FALSE) {
    .Call(`_nmathopencl_rexp_opencl_cpp_export`, n, scale, verbose)
}

rwilcox_opencl_cpp_export <- function(n, m, n2, verbose = FALSE) {
    .Call(`_nmathopencl_rwilcox_opencl_cpp_export`, n, m, n2, verbose)
}

rbinom_opencl_cpp_export <- function(n, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_rbinom_opencl_cpp_export`, n, size, prob, verbose)
}

r_pow_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_r_pow_opencl_cpp_export`, n, x, y, verbose)
}

r_pow_di_opencl_cpp_export <- function(n, x, n_exp, verbose = FALSE) {
    .Call(`_nmathopencl_r_pow_di_opencl_cpp_export`, n, x, n_exp, verbose)
}

log1pmx_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_log1pmx_opencl_cpp_export`, n, x, verbose)
}

log1pexp_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_log1pexp_opencl_cpp_export`, n, x, verbose)
}

log1mexp_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_log1mexp_opencl_cpp_export`, n, x, verbose)
}

lgamma1p_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_lgamma1p_opencl_cpp_export`, n, x, verbose)
}

pow1p_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_pow1p_opencl_cpp_export`, n, x, y, verbose)
}

logspace_add_opencl_cpp_export <- function(n, logx, logy, verbose = FALSE) {
    .Call(`_nmathopencl_logspace_add_opencl_cpp_export`, n, logx, logy, verbose)
}

logspace_sub_opencl_cpp_export <- function(n, logx, logy, verbose = FALSE) {
    .Call(`_nmathopencl_logspace_sub_opencl_cpp_export`, n, logx, logy, verbose)
}

logspace_sum_opencl_cpp_export <- function(n, logx, logy, verbose = FALSE) {
    .Call(`_nmathopencl_logspace_sum_opencl_cpp_export`, n, logx, logy, verbose)
}

norm_rand_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_norm_rand_opencl_cpp_export`, n, verbose)
}

unif_rand_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_unif_rand_opencl_cpp_export`, n, verbose)
}

r_unif_index_opencl_cpp_export <- function(n, dn, verbose = FALSE) {
    .Call(`_nmathopencl_r_unif_index_opencl_cpp_export`, n, dn, verbose)
}

exp_rand_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_exp_rand_opencl_cpp_export`, n, verbose)
}

pnorm_opencl_cpp_export <- function(q, mean, sd, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pnorm_opencl_cpp_export`, q, mean, sd, lower_tail, log_p, opencl_parallel_code, verbose)
}

qnorm_opencl_cpp_export <- function(n, p, mu, sigma, verbose = FALSE) {
    .Call(`_nmathopencl_qnorm_opencl_cpp_export`, n, p, mu, sigma, verbose)
}

dunif_opencl_cpp_export <- function(n, x, min, max, verbose = FALSE) {
    .Call(`_nmathopencl_dunif_opencl_cpp_export`, n, x, min, max, verbose)
}

punif_opencl_cpp_export <- function(q, min, max, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_punif_opencl_cpp_export`, q, min, max, lower_tail, log_p, opencl_parallel_code, verbose)
}

qunif_opencl_cpp_export <- function(n, p, min, max, verbose = FALSE) {
    .Call(`_nmathopencl_qunif_opencl_cpp_export`, n, p, min, max, verbose)
}

dgamma_opencl_cpp_export <- function(n, x, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_dgamma_opencl_cpp_export`, n, x, shape, scale, verbose)
}

pgamma_opencl_cpp_export <- function(q, shape, scale, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pgamma_opencl_cpp_export`, q, shape, scale, lower_tail, log_p, opencl_parallel_code, verbose)
}

qgamma_opencl_cpp_export <- function(n, p, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_qgamma_opencl_cpp_export`, n, p, shape, scale, verbose)
}

rgamma_opencl_cpp_export <- function(n, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_rgamma_opencl_cpp_export`, n, shape, scale, verbose)
}

dbeta_opencl_cpp_export <- function(n, x, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_dbeta_opencl_cpp_export`, n, x, a, b, verbose)
}

pbeta_opencl_cpp_export <- function(q, shape1, shape2, ncp, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pbeta_opencl_cpp_export`, q, shape1, shape2, ncp, lower_tail, log_p, opencl_parallel_code, verbose)
}

qbeta_opencl_cpp_export <- function(n, p, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_qbeta_opencl_cpp_export`, n, p, a, b, verbose)
}

rbeta_opencl_cpp_export <- function(n, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_rbeta_opencl_cpp_export`, n, a, b, verbose)
}

dlnorm_opencl_cpp_export <- function(n, x, meanlog, sdlog, verbose = FALSE) {
    .Call(`_nmathopencl_dlnorm_opencl_cpp_export`, n, x, meanlog, sdlog, verbose)
}

plnorm_opencl_cpp_export <- function(q, meanlog, sdlog, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_plnorm_opencl_cpp_export`, q, meanlog, sdlog, lower_tail, log_p, opencl_parallel_code, verbose)
}

qlnorm_opencl_cpp_export <- function(n, p, meanlog, sdlog, verbose = FALSE) {
    .Call(`_nmathopencl_qlnorm_opencl_cpp_export`, n, p, meanlog, sdlog, verbose)
}

rlnorm_opencl_cpp_export <- function(n, meanlog, sdlog, verbose = FALSE) {
    .Call(`_nmathopencl_rlnorm_opencl_cpp_export`, n, meanlog, sdlog, verbose)
}

dchisq_opencl_cpp_export <- function(n, x, df, verbose = FALSE) {
    .Call(`_nmathopencl_dchisq_opencl_cpp_export`, n, x, df, verbose)
}

pchisq_opencl_cpp_export <- function(q, df, ncp, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pchisq_opencl_cpp_export`, q, df, ncp, lower_tail, log_p, opencl_parallel_code, verbose)
}

qchisq_opencl_cpp_export <- function(n, p, df, verbose = FALSE) {
    .Call(`_nmathopencl_qchisq_opencl_cpp_export`, n, p, df, verbose)
}

rchisq_opencl_cpp_export <- function(n, df, verbose = FALSE) {
    .Call(`_nmathopencl_rchisq_opencl_cpp_export`, n, df, verbose)
}

dnchisq_opencl_cpp_export <- function(n, x, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_dnchisq_opencl_cpp_export`, n, x, df, ncp, verbose)
}

rnchisq_opencl_cpp_export <- function(n, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_rnchisq_opencl_cpp_export`, n, df, ncp, verbose)
}

df_opencl_cpp_export <- function(n, x, df1, df2, verbose = FALSE) {
    .Call(`_nmathopencl_df_opencl_cpp_export`, n, x, df1, df2, verbose)
}

pf_opencl_cpp_export <- function(q, df1, df2, ncp, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pf_opencl_cpp_export`, q, df1, df2, ncp, lower_tail, log_p, opencl_parallel_code, verbose)
}

qf_opencl_cpp_export <- function(n, p, df1, df2, verbose = FALSE) {
    .Call(`_nmathopencl_qf_opencl_cpp_export`, n, p, df1, df2, verbose)
}

rf_opencl_cpp_export <- function(n, df1, df2, verbose = FALSE) {
    .Call(`_nmathopencl_rf_opencl_cpp_export`, n, df1, df2, verbose)
}

dt_opencl_cpp_export <- function(n, x, df, verbose = FALSE) {
    .Call(`_nmathopencl_dt_opencl_cpp_export`, n, x, df, verbose)
}

pt_opencl_cpp_export <- function(q, df, ncp, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pt_opencl_cpp_export`, q, df, ncp, lower_tail, log_p, opencl_parallel_code, verbose)
}

qt_opencl_cpp_export <- function(n, p, df, verbose = FALSE) {
    .Call(`_nmathopencl_qt_opencl_cpp_export`, n, p, df, verbose)
}

rt_opencl_cpp_export <- function(n, df, verbose = FALSE) {
    .Call(`_nmathopencl_rt_opencl_cpp_export`, n, df, verbose)
}

dbinom_raw_opencl_cpp_export <- function(n, x, n_size, prob, qprob, verbose = FALSE) {
    .Call(`_nmathopencl_dbinom_raw_opencl_cpp_export`, n, x, n_size, prob, qprob, verbose)
}

dbinom_opencl_cpp_export <- function(n, x, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_dbinom_opencl_cpp_export`, n, x, size, prob, verbose)
}

pbinom_opencl_cpp_export <- function(q, size, prob, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pbinom_opencl_cpp_export`, q, size, prob, lower_tail, log_p, opencl_parallel_code, verbose)
}

dnbinom_opencl_cpp_export <- function(n, x, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_dnbinom_opencl_cpp_export`, n, x, size, prob, verbose)
}

pnbinom_opencl_cpp_export <- function(q, size, prob, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pnbinom_opencl_cpp_export`, q, size, prob, lower_tail, log_p, opencl_parallel_code, verbose)
}

qnbinom_opencl_cpp_export <- function(n, p, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_qnbinom_opencl_cpp_export`, n, p, size, prob, verbose)
}

rnbinom_opencl_cpp_export <- function(n, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_rnbinom_opencl_cpp_export`, n, size, prob, verbose)
}

dnbinom_mu_opencl_cpp_export <- function(n, x, size, mu, verbose = FALSE) {
    .Call(`_nmathopencl_dnbinom_mu_opencl_cpp_export`, n, x, size, mu, verbose)
}

pnbinom_mu_opencl_cpp_export <- function(q, size, mu, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pnbinom_mu_opencl_cpp_export`, q, size, mu, lower_tail, log_p, opencl_parallel_code, verbose)
}

rmultinom_opencl_cpp_export <- function(n, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_rmultinom_opencl_cpp_export`, n, size, prob, verbose)
}

dcauchy_opencl_cpp_export <- function(n, x, location, scale, verbose = FALSE) {
    .Call(`_nmathopencl_dcauchy_opencl_cpp_export`, n, x, location, scale, verbose)
}

pcauchy_opencl_cpp_export <- function(q, location, scale, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pcauchy_opencl_cpp_export`, q, location, scale, lower_tail, log_p, opencl_parallel_code, verbose)
}

qcauchy_opencl_cpp_export <- function(n, p, location, scale, verbose = FALSE) {
    .Call(`_nmathopencl_qcauchy_opencl_cpp_export`, n, p, location, scale, verbose)
}

rcauchy_opencl_cpp_export <- function(n, location, scale, verbose = FALSE) {
    .Call(`_nmathopencl_rcauchy_opencl_cpp_export`, n, location, scale, verbose)
}

dexp_opencl_cpp_export <- function(n, x, rate, verbose = FALSE) {
    .Call(`_nmathopencl_dexp_opencl_cpp_export`, n, x, rate, verbose)
}

pexp_opencl_cpp_export <- function(q, rate, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pexp_opencl_cpp_export`, q, rate, lower_tail, log_p, opencl_parallel_code, verbose)
}

qexp_opencl_cpp_export <- function(n, p, rate, verbose = FALSE) {
    .Call(`_nmathopencl_qexp_opencl_cpp_export`, n, p, rate, verbose)
}

dgeom_opencl_cpp_export <- function(n, x, prob, verbose = FALSE) {
    .Call(`_nmathopencl_dgeom_opencl_cpp_export`, n, x, prob, verbose)
}

pgeom_opencl_cpp_export <- function(q, prob, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pgeom_opencl_cpp_export`, q, prob, lower_tail, log_p, opencl_parallel_code, verbose)
}

qgeom_opencl_cpp_export <- function(n, p, prob, verbose = FALSE) {
    .Call(`_nmathopencl_qgeom_opencl_cpp_export`, n, p, prob, verbose)
}

rgeom_opencl_cpp_export <- function(n, prob, verbose = FALSE) {
    .Call(`_nmathopencl_rgeom_opencl_cpp_export`, n, prob, verbose)
}

dhyper_opencl_cpp_export <- function(n, x, r, b, n1, verbose = FALSE) {
    .Call(`_nmathopencl_dhyper_opencl_cpp_export`, n, x, r, b, n1, verbose)
}

phyper_opencl_cpp_export <- function(q, m, n_black, k, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_phyper_opencl_cpp_export`, q, m, n_black, k, lower_tail, log_p, opencl_parallel_code, verbose)
}

qhyper_opencl_cpp_export <- function(n, p, r, b, n1, verbose = FALSE) {
    .Call(`_nmathopencl_qhyper_opencl_cpp_export`, n, p, r, b, n1, verbose)
}

rhyper_opencl_cpp_export <- function(n, r, b, n1, verbose = FALSE) {
    .Call(`_nmathopencl_rhyper_opencl_cpp_export`, n, r, b, n1, verbose)
}

qbinom_opencl_cpp_export <- function(n, p, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_qbinom_opencl_cpp_export`, n, p, size, prob, verbose)
}

qpois_opencl_cpp_export <- function(n, p, lambda, verbose = FALSE) {
    .Call(`_nmathopencl_qpois_opencl_cpp_export`, n, p, lambda, verbose)
}

dpois_raw_opencl_cpp_export <- function(n, x, lambda, verbose = FALSE) {
    .Call(`_nmathopencl_dpois_raw_opencl_cpp_export`, n, x, lambda, verbose)
}

dpois_opencl_cpp_export <- function(n, x, lambda, verbose = FALSE) {
    .Call(`_nmathopencl_dpois_opencl_cpp_export`, n, x, lambda, verbose)
}

ppois_opencl_cpp_export <- function(q, lambda, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_ppois_opencl_cpp_export`, q, lambda, lower_tail, log_p, opencl_parallel_code, verbose)
}

qnbinom_mu_opencl_cpp_export <- function(n, p, size, mu, verbose = FALSE) {
    .Call(`_nmathopencl_qnbinom_mu_opencl_cpp_export`, n, p, size, mu, verbose)
}

rpois_opencl_cpp_export <- function(n, lambda, verbose = FALSE) {
    .Call(`_nmathopencl_rpois_opencl_cpp_export`, n, lambda, verbose)
}

rnbinom_mu_opencl_cpp_export <- function(n, size, mu, verbose = FALSE) {
    .Call(`_nmathopencl_rnbinom_mu_opencl_cpp_export`, n, size, mu, verbose)
}

dweibull_opencl_cpp_export <- function(n, x, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_dweibull_opencl_cpp_export`, n, x, shape, scale, verbose)
}

pweibull_opencl_cpp_export <- function(q, shape, scale, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pweibull_opencl_cpp_export`, q, shape, scale, lower_tail, log_p, opencl_parallel_code, verbose)
}

qweibull_opencl_cpp_export <- function(n, p, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_qweibull_opencl_cpp_export`, n, p, shape, scale, verbose)
}

rweibull_opencl_cpp_export <- function(n, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_rweibull_opencl_cpp_export`, n, shape, scale, verbose)
}

dlogis_opencl_cpp_export <- function(n, x, location, scale, verbose = FALSE) {
    .Call(`_nmathopencl_dlogis_opencl_cpp_export`, n, x, location, scale, verbose)
}

plogis_opencl_cpp_export <- function(q, location, scale, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_plogis_opencl_cpp_export`, q, location, scale, lower_tail, log_p, opencl_parallel_code, verbose)
}

qlogis_opencl_cpp_export <- function(n, p, location, scale, verbose = FALSE) {
    .Call(`_nmathopencl_qlogis_opencl_cpp_export`, n, p, location, scale, verbose)
}

rlogis_opencl_cpp_export <- function(n, location, scale, verbose = FALSE) {
    .Call(`_nmathopencl_rlogis_opencl_cpp_export`, n, location, scale, verbose)
}

qnchisq_opencl_cpp_export <- function(n, p, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnchisq_opencl_cpp_export`, n, p, df, ncp, verbose)
}

dnf_opencl_cpp_export <- function(n, x, df1, df2, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_dnf_opencl_cpp_export`, n, x, df1, df2, ncp, verbose)
}

qnf_opencl_cpp_export <- function(n, p, df1, df2, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnf_opencl_cpp_export`, n, p, df1, df2, ncp, verbose)
}

qnbeta_opencl_cpp_export <- function(n, p, a, b, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnbeta_opencl_cpp_export`, n, p, a, b, ncp, verbose)
}

dnbeta_opencl_cpp_export <- function(n, x, a, b, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_dnbeta_opencl_cpp_export`, n, x, a, b, ncp, verbose)
}

dnt_opencl_cpp_export <- function(n, x, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_dnt_opencl_cpp_export`, n, x, df, ncp, verbose)
}

qnt_opencl_cpp_export <- function(n, p, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnt_opencl_cpp_export`, n, p, df, ncp, verbose)
}

ptukey_opencl_cpp_export <- function(q, nmeans, df, nranges, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_ptukey_opencl_cpp_export`, q, nmeans, df, nranges, lower_tail, log_p, opencl_parallel_code, verbose)
}

qtukey_opencl_cpp_export <- function(n, p, nmeans, df, nranges, verbose = FALSE) {
    .Call(`_nmathopencl_qtukey_opencl_cpp_export`, n, p, nmeans, df, nranges, verbose)
}

dwilcox_opencl_cpp_export <- function(n, x, m, n2, verbose = FALSE) {
    .Call(`_nmathopencl_dwilcox_opencl_cpp_export`, n, x, m, n2, verbose)
}

pwilcox_opencl_cpp_export <- function(q, m, n2, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_pwilcox_opencl_cpp_export`, q, m, n2, lower_tail, log_p, opencl_parallel_code, verbose)
}

qwilcox_opencl_cpp_export <- function(n, p, m, n2, verbose = FALSE) {
    .Call(`_nmathopencl_qwilcox_opencl_cpp_export`, n, p, m, n2, verbose)
}

dsignrank_opencl_cpp_export <- function(n, x, nsize, verbose = FALSE) {
    .Call(`_nmathopencl_dsignrank_opencl_cpp_export`, n, x, nsize, verbose)
}

psignrank_opencl_cpp_export <- function(q, nsize, lower_tail, log_p, opencl_parallel_code, verbose = FALSE) {
    .Call(`_nmathopencl_psignrank_opencl_cpp_export`, q, nsize, lower_tail, log_p, opencl_parallel_code, verbose)
}

qsignrank_opencl_cpp_export <- function(n, p, nsize, verbose = FALSE) {
    .Call(`_nmathopencl_qsignrank_opencl_cpp_export`, n, p, nsize, verbose)
}

rsignrank_opencl_cpp_export <- function(n, nsize, verbose = FALSE) {
    .Call(`_nmathopencl_rsignrank_opencl_cpp_export`, n, nsize, verbose)
}

gammafn_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_gammafn_opencl_cpp_export`, n, x, verbose)
}

lgammafn_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_lgammafn_opencl_cpp_export`, n, x, verbose)
}

lgammafn_sign_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_lgammafn_sign_opencl_cpp_export`, n, x, verbose)
}

dpsifn_opencl_cpp_export <- function(n, x, n_deriv, kode, m, verbose = FALSE) {
    .Call(`_nmathopencl_dpsifn_opencl_cpp_export`, n, x, n_deriv, kode, m, verbose)
}

psigamma_opencl_cpp_export <- function(n, x, deriv, verbose = FALSE) {
    .Call(`_nmathopencl_psigamma_opencl_cpp_export`, n, x, deriv, verbose)
}

digamma_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_digamma_opencl_cpp_export`, n, x, verbose)
}

trigamma_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_trigamma_opencl_cpp_export`, n, x, verbose)
}

tetragamma_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_tetragamma_opencl_cpp_export`, n, x, verbose)
}

pentagamma_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_pentagamma_opencl_cpp_export`, n, x, verbose)
}

beta_opencl_cpp_export <- function(n, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_beta_opencl_cpp_export`, n, a, b, verbose)
}

lbeta_opencl_cpp_export <- function(n, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_lbeta_opencl_cpp_export`, n, a, b, verbose)
}

choose_opencl_cpp_export <- function(n, n_val, k, verbose = FALSE) {
    .Call(`_nmathopencl_choose_opencl_cpp_export`, n, n_val, k, verbose)
}

lchoose_opencl_cpp_export <- function(n, n_val, k, verbose = FALSE) {
    .Call(`_nmathopencl_lchoose_opencl_cpp_export`, n, n_val, k, verbose)
}

bessel_i_opencl_cpp_export <- function(n, x, nu, expo_scaled, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_i_opencl_cpp_export`, n, x, nu, expo_scaled, verbose)
}

bessel_j_opencl_cpp_export <- function(n, x, nu, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_j_opencl_cpp_export`, n, x, nu, verbose)
}

bessel_k_opencl_cpp_export <- function(n, x, nu, expo_scaled, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_k_opencl_cpp_export`, n, x, nu, expo_scaled, verbose)
}

bessel_y_opencl_cpp_export <- function(n, x, nu, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_y_opencl_cpp_export`, n, x, nu, verbose)
}

bessel_i_ex_opencl_cpp_export <- function(n, x, nu, expo, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_i_ex_opencl_cpp_export`, n, x, nu, expo, verbose)
}

bessel_j_ex_opencl_cpp_export <- function(n, x, nu, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_j_ex_opencl_cpp_export`, n, x, nu, verbose)
}

bessel_k_ex_opencl_cpp_export <- function(n, x, nu, expo, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_k_ex_opencl_cpp_export`, n, x, nu, expo, verbose)
}

bessel_y_ex_opencl_cpp_export <- function(n, x, nu, verbose = FALSE) {
    .Call(`_nmathopencl_bessel_y_ex_opencl_cpp_export`, n, x, nu, verbose)
}

imax2_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_imax2_opencl_cpp_export`, n, x, y, verbose)
}

imin2_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_imin2_opencl_cpp_export`, n, x, y, verbose)
}

fmax2_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_fmax2_opencl_cpp_export`, n, x, y, verbose)
}

fmin2_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_fmin2_opencl_cpp_export`, n, x, y, verbose)
}

sign_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_sign_opencl_cpp_export`, n, x, verbose)
}

fprec_opencl_cpp_export <- function(n, x, digits, verbose = FALSE) {
    .Call(`_nmathopencl_fprec_opencl_cpp_export`, n, x, digits, verbose)
}

fround_opencl_cpp_export <- function(n, x, digits, verbose = FALSE) {
    .Call(`_nmathopencl_fround_opencl_cpp_export`, n, x, digits, verbose)
}

fsign_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_fsign_opencl_cpp_export`, n, x, y, verbose)
}

ftrunc_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_ftrunc_opencl_cpp_export`, n, x, verbose)
}

r_check_user_interrupt_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_r_check_user_interrupt_opencl_cpp_export`, n, verbose)
}

r_check_stack_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_r_check_stack_opencl_cpp_export`, n, verbose)
}

load_kernel_source_wrapper_cpp_export <- function(relative_path, package = "nmathopencl") {
    .Call(`_nmathopencl_load_kernel_source_wrapper_cpp_export`, relative_path, package)
}

load_kernel_library_wrapper_cpp_export <- function(subdir, package = "nmathopencl", verbose = FALSE) {
    .Call(`_nmathopencl_load_kernel_library_wrapper_cpp_export`, subdir, package, verbose)
}

has_opencl_cpp_export <- function() {
    .Call(`_nmathopencl_has_opencl_cpp_export`)
}

get_opencl_core_count_cpp_export <- function() {
    .Call(`_nmathopencl_get_opencl_core_count_cpp_export`)
}

gpu_names_cpp_export <- function() {
    .Call(`_nmathopencl_gpu_names_cpp_export`)
}

