# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rNormalGLM_cpp_export <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_nmathopencl_rNormalGLM_cpp_export`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

rNormalReg_cpp_export <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "gaussian", link = "identity", Gridtype = 2L) {
    .Call(`_nmathopencl_rNormalReg_cpp_export`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

rIndepNormalGammaReg_cpp_export <- function(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar) {
    .Call(`_nmathopencl_rIndepNormalGammaReg_cpp_export`, n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar)
}

rNormalGammaReg_cpp_export <- function(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose = FALSE) {
    .Call(`_nmathopencl_rNormalGammaReg_cpp_export`, n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose)
}

rGammaGaussian_cpp_export <- function(n, y, x, beta, wt, alpha, shape, rate, disp_lower = NULL, disp_upper = NULL, verbose = FALSE) {
    .Call(`_nmathopencl_rGammaGaussian_cpp_export`, n, y, x, beta, wt, alpha, shape, rate, disp_lower, disp_upper, verbose)
}

rGammaGamma_cpp_export <- function(n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower = NULL, disp_upper = NULL, verbose = FALSE) {
    .Call(`_nmathopencl_rGammaGamma_cpp_export`, n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose)
}

rNormalGLM_std_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L, verbose = FALSE) {
    .Call(`_nmathopencl_rNormalGLM_std_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar, verbose)
}

EnvelopeSize_cpp_export <- function(a, G1, Gridtype, n, n_envopt, use_opencl, verbose) {
    .Call(`_nmathopencl_EnvelopeSize_cpp_export`, a, G1, Gridtype, n, n_envopt, use_opencl, verbose)
}

EnvelopeBuild_cpp_export <- function(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose) {
    .Call(`_nmathopencl_EnvelopeBuild_cpp_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeBuild_Ind_Normal_Gamma_cpp_export <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, n_envopt = -1L, sortgrid = FALSE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_nmathopencl_EnvelopeBuild_Ind_Normal_Gamma_cpp_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeEval_cpp_export <- function(G4, y, x, mu, P, alpha, wt, family, link, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_nmathopencl_EnvelopeEval_cpp_export`, G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose)
}

EnvelopeDispersionBuild_cpp_export <- function(Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc = 0.99, disp_lower = NULL, disp_upper = NULL, verbose = FALSE, use_parallel = TRUE) {
    .Call(`_nmathopencl_EnvelopeDispersionBuild_cpp_export`, Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc, disp_lower, disp_upper, verbose, use_parallel)
}

EnvelopeOrchestrator_cpp_export <- function(bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose) {
    .Call(`_nmathopencl_EnvelopeOrchestrator_cpp_export`, bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose)
}

EnvelopeCentering_cpp_export <- function(y, x, mu, P, offset, wt, shape, rate, Gridtype = 2L, verbose = FALSE) {
    .Call(`_nmathopencl_EnvelopeCentering_cpp_export`, y, x, mu, P, offset, wt, shape, rate, Gridtype, verbose)
}

EnvelopeSet_Grid_cpp_export <- function(GIndex, cbars, Lint) {
    .Call(`_nmathopencl_EnvelopeSet_Grid_cpp_export`, GIndex, cbars, Lint)
}

EnvelopeSet_LogP_cpp_export <- function(logP, NegLL, cbars, G3) {
    .Call(`_nmathopencl_EnvelopeSet_LogP_cpp_export`, logP, NegLL, cbars, G3)
}

rIndepNormalGammaReg_std_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_nmathopencl_rIndepNormalGammaReg_std_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

rIndepNormalGammaReg_std_parallel_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_nmathopencl_rIndepNormalGammaReg_std_parallel_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

glmb_Standardize_Model_cpp_export <- function(y, x, P, bstar, A1) {
    .Call(`_nmathopencl_glmb_Standardize_Model_cpp_export`, y, x, P, bstar, A1)
}

dnorm_opencl_cpp_export <- function(x, mu = 0.0, sigma = 1.0, give_log = FALSE, verbose = FALSE) {
    .Call(`_nmathopencl_dnorm_opencl_cpp_export`, x, mu, sigma, give_log, verbose)
}

runif_opencl_cpp_export <- function(n, a = 0.0, b = 1.0, verbose = FALSE) {
    .Call(`_nmathopencl_runif_opencl_cpp_export`, n, a, b, verbose)
}

rnorm_opencl_cpp_export <- function(n, mu = 0.0, sigma = 1.0, verbose = FALSE) {
    .Call(`_nmathopencl_rnorm_opencl_cpp_export`, n, mu, sigma, verbose)
}

rexp_opencl_cpp_export <- function(n, scale = 1.0, verbose = FALSE) {
    .Call(`_nmathopencl_rexp_opencl_cpp_export`, n, scale, verbose)
}

rwilcox_opencl_cpp_export <- function(n, m, n2, verbose = FALSE) {
    .Call(`_nmathopencl_rwilcox_opencl_cpp_export`, n, m, n2, verbose)
}

rbinom_opencl_cpp_export <- function(n, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_rbinom_opencl_cpp_export`, n, size, prob, verbose)
}

r_pow_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_r_pow_opencl_cpp_export`, n, x, y, verbose)
}

r_pow_di_opencl_cpp_export <- function(n, x, n_exp, verbose = FALSE) {
    .Call(`_nmathopencl_r_pow_di_opencl_cpp_export`, n, x, n_exp, verbose)
}

log1pmx_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_log1pmx_opencl_cpp_export`, n, x, verbose)
}

log1pexp_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_log1pexp_opencl_cpp_export`, n, x, verbose)
}

log1mexp_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_log1mexp_opencl_cpp_export`, n, x, verbose)
}

lgamma1p_opencl_cpp_export <- function(n, x, verbose = FALSE) {
    .Call(`_nmathopencl_lgamma1p_opencl_cpp_export`, n, x, verbose)
}

pow1p_opencl_cpp_export <- function(n, x, y, verbose = FALSE) {
    .Call(`_nmathopencl_pow1p_opencl_cpp_export`, n, x, y, verbose)
}

logspace_add_opencl_cpp_export <- function(n, logx, logy, verbose = FALSE) {
    .Call(`_nmathopencl_logspace_add_opencl_cpp_export`, n, logx, logy, verbose)
}

logspace_sub_opencl_cpp_export <- function(n, logx, logy, verbose = FALSE) {
    .Call(`_nmathopencl_logspace_sub_opencl_cpp_export`, n, logx, logy, verbose)
}

logspace_sum_opencl_cpp_export <- function(n, logx, logy, verbose = FALSE) {
    .Call(`_nmathopencl_logspace_sum_opencl_cpp_export`, n, logx, logy, verbose)
}

norm_rand_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_norm_rand_opencl_cpp_export`, n, verbose)
}

unif_rand_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_unif_rand_opencl_cpp_export`, n, verbose)
}

r_unif_index_opencl_cpp_export <- function(n, dn, verbose = FALSE) {
    .Call(`_nmathopencl_r_unif_index_opencl_cpp_export`, n, dn, verbose)
}

exp_rand_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_exp_rand_opencl_cpp_export`, n, verbose)
}

pnorm_opencl_cpp_export <- function(n, x, mu, sigma, verbose = FALSE) {
    .Call(`_nmathopencl_pnorm_opencl_cpp_export`, n, x, mu, sigma, verbose)
}

qnorm_opencl_cpp_export <- function(n, p, mu, sigma, verbose = FALSE) {
    .Call(`_nmathopencl_qnorm_opencl_cpp_export`, n, p, mu, sigma, verbose)
}

dunif_opencl_cpp_export <- function(n, x, min, max, verbose = FALSE) {
    .Call(`_nmathopencl_dunif_opencl_cpp_export`, n, x, min, max, verbose)
}

punif_opencl_cpp_export <- function(n, x, min, max, verbose = FALSE) {
    .Call(`_nmathopencl_punif_opencl_cpp_export`, n, x, min, max, verbose)
}

qunif_opencl_cpp_export <- function(n, p, min, max, verbose = FALSE) {
    .Call(`_nmathopencl_qunif_opencl_cpp_export`, n, p, min, max, verbose)
}

dgamma_opencl_cpp_export <- function(n, x, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_dgamma_opencl_cpp_export`, n, x, shape, scale, verbose)
}

pgamma_opencl_cpp_export <- function(n, x, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_pgamma_opencl_cpp_export`, n, x, shape, scale, verbose)
}

qgamma_opencl_cpp_export <- function(n, p, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_qgamma_opencl_cpp_export`, n, p, shape, scale, verbose)
}

rgamma_opencl_cpp_export <- function(n, shape, scale, verbose = FALSE) {
    .Call(`_nmathopencl_rgamma_opencl_cpp_export`, n, shape, scale, verbose)
}

dbeta_opencl_cpp_export <- function(n, x, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_dbeta_opencl_cpp_export`, n, x, a, b, verbose)
}

pbeta_opencl_cpp_export <- function(n, x, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_pbeta_opencl_cpp_export`, n, x, a, b, verbose)
}

qbeta_opencl_cpp_export <- function(n, p, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_qbeta_opencl_cpp_export`, n, p, a, b, verbose)
}

rbeta_opencl_cpp_export <- function(n, a, b, verbose = FALSE) {
    .Call(`_nmathopencl_rbeta_opencl_cpp_export`, n, a, b, verbose)
}

dlnorm_opencl_cpp_export <- function(n, x, meanlog, sdlog, verbose = FALSE) {
    .Call(`_nmathopencl_dlnorm_opencl_cpp_export`, n, x, meanlog, sdlog, verbose)
}

plnorm_opencl_cpp_export <- function(n, q, meanlog, sdlog, verbose = FALSE) {
    .Call(`_nmathopencl_plnorm_opencl_cpp_export`, n, q, meanlog, sdlog, verbose)
}

qlnorm_opencl_cpp_export <- function(n, p, meanlog, sdlog, verbose = FALSE) {
    .Call(`_nmathopencl_qlnorm_opencl_cpp_export`, n, p, meanlog, sdlog, verbose)
}

rlnorm_opencl_cpp_export <- function(n, meanlog, sdlog, verbose = FALSE) {
    .Call(`_nmathopencl_rlnorm_opencl_cpp_export`, n, meanlog, sdlog, verbose)
}

dchisq_opencl_cpp_export <- function(n, x, df, verbose = FALSE) {
    .Call(`_nmathopencl_dchisq_opencl_cpp_export`, n, x, df, verbose)
}

pchisq_opencl_cpp_export <- function(n, x, df, verbose = FALSE) {
    .Call(`_nmathopencl_pchisq_opencl_cpp_export`, n, x, df, verbose)
}

qchisq_opencl_cpp_export <- function(n, p, df, verbose = FALSE) {
    .Call(`_nmathopencl_qchisq_opencl_cpp_export`, n, p, df, verbose)
}

rchisq_opencl_cpp_export <- function(n, df, verbose = FALSE) {
    .Call(`_nmathopencl_rchisq_opencl_cpp_export`, n, df, verbose)
}

dnchisq_opencl_cpp_export <- function(n, x, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_dnchisq_opencl_cpp_export`, n, x, df, ncp, verbose)
}

rnchisq_opencl_cpp_export <- function(n, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_rnchisq_opencl_cpp_export`, n, df, ncp, verbose)
}

df_opencl_cpp_export <- function(n, x, df1, df2, verbose = FALSE) {
    .Call(`_nmathopencl_df_opencl_cpp_export`, n, x, df1, df2, verbose)
}

pf_opencl_cpp_export <- function(n, x, df1, df2, verbose = FALSE) {
    .Call(`_nmathopencl_pf_opencl_cpp_export`, n, x, df1, df2, verbose)
}

qf_opencl_cpp_export <- function(n, p, df1, df2, verbose = FALSE) {
    .Call(`_nmathopencl_qf_opencl_cpp_export`, n, p, df1, df2, verbose)
}

rf_opencl_cpp_export <- function(n, df1, df2, verbose = FALSE) {
    .Call(`_nmathopencl_rf_opencl_cpp_export`, n, df1, df2, verbose)
}

dt_opencl_cpp_export <- function(n, x, df, verbose = FALSE) {
    .Call(`_nmathopencl_dt_opencl_cpp_export`, n, x, df, verbose)
}

pt_opencl_cpp_export <- function(n, x, df, verbose = FALSE) {
    .Call(`_nmathopencl_pt_opencl_cpp_export`, n, x, df, verbose)
}

qt_opencl_cpp_export <- function(n, p, df, verbose = FALSE) {
    .Call(`_nmathopencl_qt_opencl_cpp_export`, n, p, df, verbose)
}

rt_opencl_cpp_export <- function(n, df, verbose = FALSE) {
    .Call(`_nmathopencl_rt_opencl_cpp_export`, n, df, verbose)
}

qbinom_opencl_cpp_export <- function(n, p, size, prob, verbose = FALSE) {
    .Call(`_nmathopencl_qbinom_opencl_cpp_export`, n, p, size, prob, verbose)
}

qpois_opencl_cpp_export <- function(n, p, lambda, verbose = FALSE) {
    .Call(`_nmathopencl_qpois_opencl_cpp_export`, n, p, lambda, verbose)
}

qnbinom_mu_opencl_cpp_export <- function(n, p, size, mu, verbose = FALSE) {
    .Call(`_nmathopencl_qnbinom_mu_opencl_cpp_export`, n, p, size, mu, verbose)
}

rpois_opencl_cpp_export <- function(n, lambda, verbose = FALSE) {
    .Call(`_nmathopencl_rpois_opencl_cpp_export`, n, lambda, verbose)
}

pnchisq_opencl_cpp_export <- function(n, x, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_pnchisq_opencl_cpp_export`, n, x, df, ncp, verbose)
}

qnchisq_opencl_cpp_export <- function(n, p, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnchisq_opencl_cpp_export`, n, p, df, ncp, verbose)
}

pnf_opencl_cpp_export <- function(n, x, df1, df2, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_pnf_opencl_cpp_export`, n, x, df1, df2, ncp, verbose)
}

qnf_opencl_cpp_export <- function(n, p, df1, df2, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnf_opencl_cpp_export`, n, p, df1, df2, ncp, verbose)
}

pnbeta_opencl_cpp_export <- function(n, x, a, b, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_pnbeta_opencl_cpp_export`, n, x, a, b, ncp, verbose)
}

qnbeta_opencl_cpp_export <- function(n, p, a, b, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnbeta_opencl_cpp_export`, n, p, a, b, ncp, verbose)
}

pnt_opencl_cpp_export <- function(n, x, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_pnt_opencl_cpp_export`, n, x, df, ncp, verbose)
}

qnt_opencl_cpp_export <- function(n, p, df, ncp, verbose = FALSE) {
    .Call(`_nmathopencl_qnt_opencl_cpp_export`, n, p, df, ncp, verbose)
}

r_check_user_interrupt_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_r_check_user_interrupt_opencl_cpp_export`, n, verbose)
}

r_check_stack_opencl_cpp_export <- function(n, verbose = FALSE) {
    .Call(`_nmathopencl_r_check_stack_opencl_cpp_export`, n, verbose)
}

load_kernel_source_wrapper_cpp_export <- function(relative_path, package = "nmathopencl") {
    .Call(`_nmathopencl_load_kernel_source_wrapper_cpp_export`, relative_path, package)
}

load_kernel_library_wrapper_cpp_export <- function(subdir, package = "nmathopencl", verbose = FALSE) {
    .Call(`_nmathopencl_load_kernel_library_wrapper_cpp_export`, subdir, package, verbose)
}

has_opencl_cpp_export <- function() {
    .Call(`_nmathopencl_has_opencl_cpp_export`)
}

get_opencl_core_count_cpp_export <- function() {
    .Call(`_nmathopencl_get_opencl_core_count_cpp_export`)
}

gpu_names_cpp_export <- function() {
    .Call(`_nmathopencl_gpu_names_cpp_export`)
}

