# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f2_f3_non_opencl <- function(family, link, b, y, x, mu, P, alpha, wt, progbar) {
    .Call(`_glmbayes_f2_f3_non_opencl`, family, link, b, y, x, mu, P, alpha, wt, progbar)
}

EnvelopeSize <- function(a, G1, Gridtype = 2L, n = 1000L, n_envopt = -1L, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeSize`, a, G1, Gridtype, n, n_envopt, use_opencl, verbose)
}

EnvelopeEval <- function(G4, y, x, mu, P, alpha, wt, family, link, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeEval`, G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose)
}

.EnvelopeBuild_cpp <- function(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeBuild_cpp`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

.EnvelopeBuild_Ind_Normal_Gamma <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, n_envopt = -1L, sortgrid = FALSE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeBuild_Ind_Normal_Gamma`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

rss_face_at_disp <- function(dispersion, cache, cbars_j, y, x, alpha, wt) {
    .Call(`_glmbayes_rss_face_at_disp`, dispersion, cache, cbars_j, y, x, alpha, wt)
}

UB2 <- function(dispersion, cache, cbars_j, y, x, alpha, wt, rss_min_global) {
    .Call(`_glmbayes_UB2`, dispersion, cache, cbars_j, y, x, alpha, wt, rss_min_global)
}

EnvelopeDispersionBuild_cpp <- function(Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc = 0.99, disp_lower = NULL, disp_upper = NULL, verbose = FALSE, use_parallel = TRUE) {
    .Call(`_glmbayes_EnvelopeDispersionBuild_cpp`, Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc, disp_lower, disp_upper, verbose, use_parallel)
}

has_opencl <- function() {
    .Call(`_glmbayes_has_opencl`)
}

.Set_Grid_cpp <- function(GIndex, cbars, Lint) {
    .Call(`_glmbayes_Set_Grid`, GIndex, cbars, Lint)
}

.setlogP_cpp <- function(logP, NegLL, cbars, G3) {
    .Call(`_glmbayes_setlogP`, logP, NegLL, cbars, G3)
}

gpu_names <- function() {
    .Call(`_glmbayes_gpu_names`)
}

f2_f3_opencl <- function(family, link, b, y, x, mu, P, alpha, wt, progbar) {
    .Call(`_glmbayes_f2_f3_opencl`, family, link, b, y, x, mu, P, alpha, wt, progbar)
}

load_kernel_source_wrapper <- function(relative_path, package = "glmbayes") {
    .Call(`_glmbayes_load_kernel_source_wrapper`, relative_path, package)
}

load_kernel_library_wrapper <- function(subdir, package = "glmbayes", verbose = FALSE) {
    .Call(`_glmbayes_load_kernel_library_wrapper`, subdir, package, verbose)
}

get_opencl_core_count <- function() {
    .Call(`_glmbayes_get_opencl_core_count`)
}

.rindep_norm_gamma_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

.rindep_norm_gamma_reg_std_parallel_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_parallel_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

.glmb_Standardize_Model_cpp <- function(y, x, P, bstar, A1) {
    .Call(`_glmbayes_glmb_Standardize_Model`, y, x, P, bstar, A1)
}

.rnnorm_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L, verbose = FALSE) {
    .Call(`_glmbayes_rnnorm_reg_std_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar, verbose)
}

.rnnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_rnnorm_reg_cpp`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

.rnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "gaussian", link = "identity", Gridtype = 2L) {
    .Call(`_glmbayes_rnorm_reg_cpp`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

